// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-journey/internal/sdk/models/shared"
	"net/http"
)

type CreateJourneyRequest struct {
	// Payload
	JourneyCreationRequest *shared.JourneyCreationRequest `request:"mediaType=application/json"`
	// skip creating an Automation (it takes Yn format "true, yes, 1, y")
	SkipAutomation *string `queryParam:"style=form,explode=true,name=skipAutomation"`
}

func (c *CreateJourneyRequest) GetJourneyCreationRequest() *shared.JourneyCreationRequest {
	if c == nil {
		return nil
	}
	return c.JourneyCreationRequest
}

func (c *CreateJourneyRequest) GetSkipAutomation() *string {
	if c == nil {
		return nil
	}
	return c.SkipAutomation
}

type CreateJourneyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	Journey *shared.Journey
	// Validation failed (when validation mode is STRICT)
	JourneyValidationError *shared.JourneyValidationError
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *CreateJourneyResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateJourneyResponse) GetJourney() *shared.Journey {
	if c == nil {
		return nil
	}
	return c.Journey
}

func (c *CreateJourneyResponse) GetJourneyValidationError() *shared.JourneyValidationError {
	if c == nil {
		return nil
	}
	return c.JourneyValidationError
}

func (c *CreateJourneyResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateJourneyResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}
