// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-journey/internal/sdk/models/shared"
	"net/http"
)

type GenerateDocumentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Generated document output
	GenerateDocumentResponse *shared.GenerateDocumentResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GenerateDocumentResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GenerateDocumentResponse) GetGenerateDocumentResponse() *shared.GenerateDocumentResponse {
	if o == nil {
		return nil
	}
	return o.GenerateDocumentResponse
}

func (o *GenerateDocumentResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GenerateDocumentResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
