// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-journey/internal/sdk/models/shared"
	"net/http"
)

type GetButtonOptionsRequest struct {
	// file id to get button options from
	FileID string `queryParam:"style=form,explode=true,name=fileId"`
}

func (o *GetButtonOptionsRequest) GetFileID() string {
	if o == nil {
		return ""
	}
	return o.FileID
}

// GetButtonOptionsJourneysResponseResponseBody - Internal Server Error
type GetButtonOptionsJourneysResponseResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (o *GetButtonOptionsJourneysResponseResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

// GetButtonOptionsJourneysResponseBody - Not found
type GetButtonOptionsJourneysResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (o *GetButtonOptionsJourneysResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

// GetButtonOptionsResponseBody - Bad Request - Invalid file or content
type GetButtonOptionsResponseBody struct {
	Details *string `json:"details,omitempty"`
	Message *string `json:"message,omitempty"`
}

func (o *GetButtonOptionsResponseBody) GetDetails() *string {
	if o == nil {
		return nil
	}
	return o.Details
}

func (o *GetButtonOptionsResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

type GetButtonOptionsResponse struct {
	// Success
	TwoHundredApplicationJSONClasses []shared.ButtonOption
	// Bad Request - Invalid file or content
	FourHundredApplicationJSONObject *GetButtonOptionsResponseBody
	// Not found
	FourHundredAndFourApplicationJSONObject *GetButtonOptionsJourneysResponseBody
	// Internal Server Error
	FiveHundredApplicationJSONObject *GetButtonOptionsJourneysResponseResponseBody
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetButtonOptionsResponse) GetTwoHundredApplicationJSONClasses() []shared.ButtonOption {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONClasses
}

func (o *GetButtonOptionsResponse) GetFourHundredApplicationJSONObject() *GetButtonOptionsResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredApplicationJSONObject
}

func (o *GetButtonOptionsResponse) GetFourHundredAndFourApplicationJSONObject() *GetButtonOptionsJourneysResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredAndFourApplicationJSONObject
}

func (o *GetButtonOptionsResponse) GetFiveHundredApplicationJSONObject() *GetButtonOptionsJourneysResponseResponseBody {
	if o == nil {
		return nil
	}
	return o.FiveHundredApplicationJSONObject
}

func (o *GetButtonOptionsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetButtonOptionsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetButtonOptionsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
