// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-journey/internal/sdk/models/shared"
	"net/http"
)

type GetJourneysByOrgIDRequest struct {
	// Hydrate
	Hydrate *string `queryParam:"style=form,explode=true,name=hydrate"`
	// Organization ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetJourneysByOrgIDRequest) GetHydrate() *string {
	if g == nil {
		return nil
	}
	return g.Hydrate
}

func (g *GetJourneysByOrgIDRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetJourneysByOrgIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	GetJourneysResponse *shared.GetJourneysResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetJourneysByOrgIDResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetJourneysByOrgIDResponse) GetGetJourneysResponse() *shared.GetJourneysResponse {
	if g == nil {
		return nil
	}
	return g.GetJourneysResponse
}

func (g *GetJourneysByOrgIDResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetJourneysByOrgIDResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
