// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-journey/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-journey/internal/sdk/models/shared"
	"net/http"
)

type GetJourneyV2Request struct {
	// Journey ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// DynamoDB version to fetch. `0` (default) is the live row; positive integers are historical snapshots created on each save. Note: this is distinct from the `revisions` counter on the row body.
	//
	Version *int64 `default:"0" queryParam:"style=form,explode=true,name=version"`
}

func (g GetJourneyV2Request) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetJourneyV2Request) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetJourneyV2Request) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetJourneyV2Request) GetVersion() *int64 {
	if g == nil {
		return nil
	}
	return g.Version
}

type GetJourneyV2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	JourneyCreationRequestV2 *shared.JourneyCreationRequestV2
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetJourneyV2Response) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetJourneyV2Response) GetJourneyCreationRequestV2() *shared.JourneyCreationRequestV2 {
	if g == nil {
		return nil
	}
	return g.JourneyCreationRequestV2
}

func (g *GetJourneyV2Response) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetJourneyV2Response) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
