// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-journey/internal/sdk/models/shared"
	"net/http"
)

type GetJourneyProductsRequest struct {
	// city for availibility
	City *string `queryParam:"style=form,explode=true,name=city"`
	// Journey ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Zip Code for availibility
	PostalCode *string `queryParam:"style=form,explode=true,name=postal_code"`
	// What source ID. Journey or Entity ID
	Source *string `queryParam:"style=form,explode=true,name=source"`
	// street name for availibility
	Street *string `queryParam:"style=form,explode=true,name=street"`
	// street number for availibility
	StreetNumber *string `queryParam:"style=form,explode=true,name=street_number"`
}

func (g *GetJourneyProductsRequest) GetCity() *string {
	if g == nil {
		return nil
	}
	return g.City
}

func (g *GetJourneyProductsRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetJourneyProductsRequest) GetPostalCode() *string {
	if g == nil {
		return nil
	}
	return g.PostalCode
}

func (g *GetJourneyProductsRequest) GetSource() *string {
	if g == nil {
		return nil
	}
	return g.Source
}

func (g *GetJourneyProductsRequest) GetStreet() *string {
	if g == nil {
		return nil
	}
	return g.Street
}

func (g *GetJourneyProductsRequest) GetStreetNumber() *string {
	if g == nil {
		return nil
	}
	return g.StreetNumber
}

type GetJourneyProductsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	JourneyProductsResponse []shared.JourneyProductsResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetJourneyProductsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetJourneyProductsResponse) GetJourneyProductsResponse() []shared.JourneyProductsResponse {
	if g == nil {
		return nil
	}
	return g.JourneyProductsResponse
}

func (g *GetJourneyProductsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetJourneyProductsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
