// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-journey/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-journey/internal/sdk/models/shared"
	"net/http"
)

type GetJourneySecurity struct {
	EpilotAuth *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	PortalAuth *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (g *GetJourneySecurity) GetEpilotAuth() *string {
	if g == nil {
		return nil
	}
	return g.EpilotAuth
}

func (g *GetJourneySecurity) GetPortalAuth() *string {
	if g == nil {
		return nil
	}
	return g.PortalAuth
}

type GetJourneyRequest struct {
	// Journey ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Organization ID
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
	// What source ID. Journey or Entity ID
	Source *string `queryParam:"style=form,explode=true,name=source"`
	// DynamoDB version to fetch. `0` (default) is the live row; positive integers are historical snapshots created on each save. Note: this is distinct from the `revisions` counter on the row body.
	//
	Version *int64 `default:"0" queryParam:"style=form,explode=true,name=version"`
}

func (g GetJourneyRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetJourneyRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetJourneyRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetJourneyRequest) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}

func (g *GetJourneyRequest) GetSource() *string {
	if g == nil {
		return nil
	}
	return g.Source
}

func (g *GetJourneyRequest) GetVersion() *int64 {
	if g == nil {
		return nil
	}
	return g.Version
}

type GetJourneyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	Journey *shared.Journey
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetJourneyResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetJourneyResponse) GetJourney() *shared.Journey {
	if g == nil {
		return nil
	}
	return g.Journey
}

func (g *GetJourneyResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetJourneyResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
