// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-journey/internal/sdk/models/shared"
	"net/http"
)

type GetSettingsForJourneyRequest struct {
	// Journey ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetSettingsForJourneyRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// GetSettingsForJourneyJourneysResponseBody - Internal Server Error
type GetSettingsForJourneyJourneysResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (o *GetSettingsForJourneyJourneysResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

// GetSettingsForJourneyResponseBody - Not found
type GetSettingsForJourneyResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (o *GetSettingsForJourneyResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

type GetSettingsForJourneyResponse struct {
	// Not found
	FourHundredAndFourApplicationJSONObject *GetSettingsForJourneyResponseBody
	// Internal Server Error
	FiveHundredApplicationJSONObject *GetSettingsForJourneyJourneysResponseBody
	// HTTP response content type for this operation
	ContentType string
	// Success
	GetSettingsForJourney *shared.GetSettingsForJourney
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetSettingsForJourneyResponse) GetFourHundredAndFourApplicationJSONObject() *GetSettingsForJourneyResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredAndFourApplicationJSONObject
}

func (o *GetSettingsForJourneyResponse) GetFiveHundredApplicationJSONObject() *GetSettingsForJourneyJourneysResponseBody {
	if o == nil {
		return nil
	}
	return o.FiveHundredApplicationJSONObject
}

func (o *GetSettingsForJourneyResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetSettingsForJourneyResponse) GetGetSettingsForJourney() *shared.GetSettingsForJourney {
	if o == nil {
		return nil
	}
	return o.GetSettingsForJourney
}

func (o *GetSettingsForJourneyResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetSettingsForJourneyResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
