// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-journey/internal/sdk/models/shared"
	"net/http"
)

// PatchUpdateJourneyV2ResponseBody - Journey or associated entity not found
type PatchUpdateJourneyV2ResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (p *PatchUpdateJourneyV2ResponseBody) GetMessage() *string {
	if p == nil {
		return nil
	}
	return p.Message
}

// #region class-body-patchupdatejourneyv2responsebody
// #endregion class-body-patchupdatejourneyv2responsebody

type PatchUpdateJourneyV2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	JourneyCreationRequestV2 *shared.JourneyCreationRequestV2
	// Validation failed (when validation mode is STRICT)
	JourneyValidationError *shared.JourneyValidationError
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Journey or associated entity not found
	Object *PatchUpdateJourneyV2ResponseBody
}

func (p *PatchUpdateJourneyV2Response) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PatchUpdateJourneyV2Response) GetJourneyCreationRequestV2() *shared.JourneyCreationRequestV2 {
	if p == nil {
		return nil
	}
	return p.JourneyCreationRequestV2
}

func (p *PatchUpdateJourneyV2Response) GetJourneyValidationError() *shared.JourneyValidationError {
	if p == nil {
		return nil
	}
	return p.JourneyValidationError
}

func (p *PatchUpdateJourneyV2Response) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PatchUpdateJourneyV2Response) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PatchUpdateJourneyV2Response) GetObject() *PatchUpdateJourneyV2ResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}

// #region class-body-patchupdatejourneyv2response
// #endregion class-body-patchupdatejourneyv2response
