// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-journey/internal/sdk/models/shared"
	"net/http"
)

// PatchUpdateJourneyResponseBody - Journey or associated entity not found
type PatchUpdateJourneyResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (o *PatchUpdateJourneyResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

type PatchUpdateJourneyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	JourneyResponse *shared.JourneyResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Journey or associated entity not found
	Object *PatchUpdateJourneyResponseBody
}

func (o *PatchUpdateJourneyResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PatchUpdateJourneyResponse) GetJourneyResponse() *shared.JourneyResponse {
	if o == nil {
		return nil
	}
	return o.JourneyResponse
}

func (o *PatchUpdateJourneyResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PatchUpdateJourneyResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PatchUpdateJourneyResponse) GetObject() *PatchUpdateJourneyResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
