// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-journey/internal/sdk/models/shared"
	"net/http"
)

// PatchUpdateJourneyResponseBody - Journey or associated entity not found
type PatchUpdateJourneyResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (p *PatchUpdateJourneyResponseBody) GetMessage() *string {
	if p == nil {
		return nil
	}
	return p.Message
}

type PatchUpdateJourneyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	JourneyResponse *shared.JourneyResponse
	// Validation failed (when validation mode is STRICT)
	JourneyValidationError *shared.JourneyValidationError
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Journey or associated entity not found
	Object *PatchUpdateJourneyResponseBody
}

func (p *PatchUpdateJourneyResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PatchUpdateJourneyResponse) GetJourneyResponse() *shared.JourneyResponse {
	if p == nil {
		return nil
	}
	return p.JourneyResponse
}

func (p *PatchUpdateJourneyResponse) GetJourneyValidationError() *shared.JourneyValidationError {
	if p == nil {
		return nil
	}
	return p.JourneyValidationError
}

func (p *PatchUpdateJourneyResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PatchUpdateJourneyResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PatchUpdateJourneyResponse) GetObject() *PatchUpdateJourneyResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}
