// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type RemoveJourneyV2Request struct {
	// Journey ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (r *RemoveJourneyV2Request) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

type RemoveJourneyV2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (r *RemoveJourneyV2Response) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *RemoveJourneyV2Response) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *RemoveJourneyV2Response) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}
