// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type RemoveJourneyRequest struct {
	// Journey ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *RemoveJourneyRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// RemoveJourneyResponseBody - Journey not found
type RemoveJourneyResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (o *RemoveJourneyResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

type RemoveJourneyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Journey not found
	Object *RemoveJourneyResponseBody
}

func (o *RemoveJourneyResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *RemoveJourneyResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *RemoveJourneyResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *RemoveJourneyResponse) GetObject() *RemoveJourneyResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
