// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-journey/internal/sdk/models/shared"
	"net/http"
)

type SearchJourneysResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	SearchJourneysResponse *shared.SearchJourneysResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (s *SearchJourneysResponse) GetContentType() string {
	if s == nil {
		return ""
	}
	return s.ContentType
}

func (s *SearchJourneysResponse) GetSearchJourneysResponse() *shared.SearchJourneysResponse {
	if s == nil {
		return nil
	}
	return s.SearchJourneysResponse
}

func (s *SearchJourneysResponse) GetStatusCode() int {
	if s == nil {
		return 0
	}
	return s.StatusCode
}

func (s *SearchJourneysResponse) GetRawResponse() *http.Response {
	if s == nil {
		return nil
	}
	return s.RawResponse
}
