// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-journey/internal/sdk/models/shared"
	"net/http"
)

// UpdateJourneyV2ResponseBody - Journey or associated entity not found
type UpdateJourneyV2ResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (u *UpdateJourneyV2ResponseBody) GetMessage() *string {
	if u == nil {
		return nil
	}
	return u.Message
}

type UpdateJourneyV2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	JourneyCreationRequestV2 *shared.JourneyCreationRequestV2
	// Validation failed (when validation mode is STRICT)
	JourneyValidationError *shared.JourneyValidationError
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Journey or associated entity not found
	Object *UpdateJourneyV2ResponseBody
}

func (u *UpdateJourneyV2Response) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateJourneyV2Response) GetJourneyCreationRequestV2() *shared.JourneyCreationRequestV2 {
	if u == nil {
		return nil
	}
	return u.JourneyCreationRequestV2
}

func (u *UpdateJourneyV2Response) GetJourneyValidationError() *shared.JourneyValidationError {
	if u == nil {
		return nil
	}
	return u.JourneyValidationError
}

func (u *UpdateJourneyV2Response) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateJourneyV2Response) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateJourneyV2Response) GetObject() *UpdateJourneyV2ResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}
