// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-journey/internal/sdk/models/shared"
	"net/http"
)

type UpdateJourneyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// Validation failed (when validation mode is STRICT)
	JourneyValidationError *shared.JourneyValidationError
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (u *UpdateJourneyResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateJourneyResponse) GetHeaders() map[string][]string {
	if u == nil {
		return map[string][]string{}
	}
	return u.Headers
}

func (u *UpdateJourneyResponse) GetJourneyValidationError() *shared.JourneyValidationError {
	if u == nil {
		return nil
	}
	return u.JourneyValidationError
}

func (u *UpdateJourneyResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateJourneyResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}
