// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-journey/internal/sdk/models/shared"
	"net/http"
)

// UpdateJourneyV2ResponseBody - Journey or associated entity not found
type UpdateJourneyV2ResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (o *UpdateJourneyV2ResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

type UpdateJourneyV2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	JourneyCreationRequestV2 *shared.JourneyCreationRequestV2
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Journey or associated entity not found
	Object *UpdateJourneyV2ResponseBody
}

func (o *UpdateJourneyV2Response) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateJourneyV2Response) GetJourneyCreationRequestV2() *shared.JourneyCreationRequestV2 {
	if o == nil {
		return nil
	}
	return o.JourneyCreationRequestV2
}

func (o *UpdateJourneyV2Response) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateJourneyV2Response) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateJourneyV2Response) GetObject() *UpdateJourneyV2ResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
