// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type JourneyV2Design struct {
	LogoURL *string                `json:"logoUrl,omitempty"`
	Theme   map[string]interface{} `json:"theme,omitempty"`
}

func (o *JourneyV2Design) GetLogoURL() *string {
	if o == nil {
		return nil
	}
	return o.LogoURL
}

func (o *JourneyV2Design) GetTheme() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.Theme
}

type JourneyV2Logics struct {
	Actions         []string `json:"actions"`
	AutoGeneratedID *string  `json:"autoGeneratedId,omitempty"`
	Conditions      []string `json:"conditions"`
}

func (o *JourneyV2Logics) GetActions() []string {
	if o == nil {
		return []string{}
	}
	return o.Actions
}

func (o *JourneyV2Logics) GetAutoGeneratedID() *string {
	if o == nil {
		return nil
	}
	return o.AutoGeneratedID
}

func (o *JourneyV2Logics) GetConditions() []string {
	if o == nil {
		return []string{}
	}
	return o.Conditions
}

type JourneyV2SourceType string

const (
	JourneyV2SourceTypeJourney JourneyV2SourceType = "journey"
	JourneyV2SourceTypeStep    JourneyV2SourceType = "step"
	JourneyV2SourceTypeBlock   JourneyV2SourceType = "block"
)

func (e JourneyV2SourceType) ToPointer() *JourneyV2SourceType {
	return &e
}

func (e *JourneyV2SourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "journey":
		fallthrough
	case "step":
		fallthrough
	case "block":
		*e = JourneyV2SourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JourneyV2SourceType: %v", v)
	}
}

type JourneyV2Type string

const (
	JourneyV2TypeInject        JourneyV2Type = "inject"
	JourneyV2TypeInjectWithKey JourneyV2Type = "injectWithKey"
)

func (e JourneyV2Type) ToPointer() *JourneyV2Type {
	return &e
}

func (e *JourneyV2Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "inject":
		fallthrough
	case "injectWithKey":
		*e = JourneyV2Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JourneyV2Type: %v", v)
	}
}

type JourneyV2Rules struct {
	Source     string              `json:"source"`
	SourceType JourneyV2SourceType `json:"sourceType"`
	Target     string              `json:"target"`
	Type       JourneyV2Type       `json:"type"`
}

func (o *JourneyV2Rules) GetSource() string {
	if o == nil {
		return ""
	}
	return o.Source
}

func (o *JourneyV2Rules) GetSourceType() JourneyV2SourceType {
	if o == nil {
		return JourneyV2SourceType("")
	}
	return o.SourceType
}

func (o *JourneyV2Rules) GetTarget() string {
	if o == nil {
		return ""
	}
	return o.Target
}

func (o *JourneyV2Rules) GetType() JourneyV2Type {
	if o == nil {
		return JourneyV2Type("")
	}
	return o.Type
}

type JourneyV2Align string

const (
	JourneyV2AlignLeft   JourneyV2Align = "left"
	JourneyV2AlignCenter JourneyV2Align = "center"
	JourneyV2AlignRight  JourneyV2Align = "right"
)

func (e JourneyV2Align) ToPointer() *JourneyV2Align {
	return &e
}

func (e *JourneyV2Align) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "left":
		fallthrough
	case "center":
		fallthrough
	case "right":
		*e = JourneyV2Align(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JourneyV2Align: %v", v)
	}
}

type JourneyV2Button struct {
	Align *JourneyV2Align `json:"align,omitempty"`
	Text  *string         `json:"text,omitempty"`
}

func (o *JourneyV2Button) GetAlign() *JourneyV2Align {
	if o == nil {
		return nil
	}
	return o.Align
}

func (o *JourneyV2Button) GetText() *string {
	if o == nil {
		return nil
	}
	return o.Text
}

type JourneyV2Lang string

const (
	JourneyV2LangDe JourneyV2Lang = "de"
	JourneyV2LangEn JourneyV2Lang = "en"
	JourneyV2LangFr JourneyV2Lang = "fr"
)

func (e JourneyV2Lang) ToPointer() *JourneyV2Lang {
	return &e
}

func (e *JourneyV2Lang) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "de":
		fallthrough
	case "en":
		fallthrough
	case "fr":
		*e = JourneyV2Lang(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JourneyV2Lang: %v", v)
	}
}

type JourneyV2Mode string

const (
	JourneyV2ModeFullScreen JourneyV2Mode = "full-screen"
	JourneyV2ModeInline     JourneyV2Mode = "inline"
)

func (e JourneyV2Mode) ToPointer() *JourneyV2Mode {
	return &e
}

func (e *JourneyV2Mode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "full-screen":
		fallthrough
	case "inline":
		*e = JourneyV2Mode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JourneyV2Mode: %v", v)
	}
}

type JourneyV2EmbedOptions struct {
	Button      *JourneyV2Button `json:"button,omitempty"`
	Lang        *JourneyV2Lang   `json:"lang,omitempty"`
	Mode        *JourneyV2Mode   `json:"mode,omitempty"`
	ScrollToTop *bool            `json:"scrollToTop,omitempty"`
	TopBar      *bool            `json:"topBar,omitempty"`
	Width       *string          `json:"width,omitempty"`
}

func (o *JourneyV2EmbedOptions) GetButton() *JourneyV2Button {
	if o == nil {
		return nil
	}
	return o.Button
}

func (o *JourneyV2EmbedOptions) GetLang() *JourneyV2Lang {
	if o == nil {
		return nil
	}
	return o.Lang
}

func (o *JourneyV2EmbedOptions) GetMode() *JourneyV2Mode {
	if o == nil {
		return nil
	}
	return o.Mode
}

func (o *JourneyV2EmbedOptions) GetScrollToTop() *bool {
	if o == nil {
		return nil
	}
	return o.ScrollToTop
}

func (o *JourneyV2EmbedOptions) GetTopBar() *bool {
	if o == nil {
		return nil
	}
	return o.TopBar
}

func (o *JourneyV2EmbedOptions) GetWidth() *string {
	if o == nil {
		return nil
	}
	return o.Width
}

type JourneyV2RuntimeEntities string

const (
	JourneyV2RuntimeEntitiesOrder       JourneyV2RuntimeEntities = "ORDER"
	JourneyV2RuntimeEntitiesOpportunity JourneyV2RuntimeEntities = "OPPORTUNITY"
)

func (e JourneyV2RuntimeEntities) ToPointer() *JourneyV2RuntimeEntities {
	return &e
}

func (e *JourneyV2RuntimeEntities) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ORDER":
		fallthrough
	case "OPPORTUNITY":
		*e = JourneyV2RuntimeEntities(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JourneyV2RuntimeEntities: %v", v)
	}
}

type JourneyV2Settings struct {
	AddressSuggestionsFileURL *string                    `json:"addressSuggestionsFileUrl,omitempty"`
	Description               *string                    `json:"description,omitempty"`
	DesignID                  *string                    `json:"designId,omitempty"`
	EmbedOptions              *JourneyV2EmbedOptions     `json:"embedOptions,omitempty"`
	EntityTags                []string                   `json:"entityTags,omitempty"`
	FilePurposes              []string                   `json:"filePurposes,omitempty"`
	MappingsAutomationID      *string                    `json:"mappingsAutomationId,omitempty"`
	RuntimeEntities           []JourneyV2RuntimeEntities `json:"runtimeEntities,omitempty"`
	SafeModeAutomation        *bool                      `json:"safeModeAutomation,omitempty"`
	TargetedCustomer          *string                    `json:"targetedCustomer,omitempty"`
	TemplateID                *string                    `json:"templateId,omitempty"`
}

func (o *JourneyV2Settings) GetAddressSuggestionsFileURL() *string {
	if o == nil {
		return nil
	}
	return o.AddressSuggestionsFileURL
}

func (o *JourneyV2Settings) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *JourneyV2Settings) GetDesignID() *string {
	if o == nil {
		return nil
	}
	return o.DesignID
}

func (o *JourneyV2Settings) GetEmbedOptions() *JourneyV2EmbedOptions {
	if o == nil {
		return nil
	}
	return o.EmbedOptions
}

func (o *JourneyV2Settings) GetEntityTags() []string {
	if o == nil {
		return nil
	}
	return o.EntityTags
}

func (o *JourneyV2Settings) GetFilePurposes() []string {
	if o == nil {
		return nil
	}
	return o.FilePurposes
}

func (o *JourneyV2Settings) GetMappingsAutomationID() *string {
	if o == nil {
		return nil
	}
	return o.MappingsAutomationID
}

func (o *JourneyV2Settings) GetRuntimeEntities() []JourneyV2RuntimeEntities {
	if o == nil {
		return nil
	}
	return o.RuntimeEntities
}

func (o *JourneyV2Settings) GetSafeModeAutomation() *bool {
	if o == nil {
		return nil
	}
	return o.SafeModeAutomation
}

func (o *JourneyV2Settings) GetTargetedCustomer() *string {
	if o == nil {
		return nil
	}
	return o.TargetedCustomer
}

func (o *JourneyV2Settings) GetTemplateID() *string {
	if o == nil {
		return nil
	}
	return o.TemplateID
}

type JourneyV2Steps struct {
	HideNextButton    *bool       `json:"hideNextButton,omitempty"`
	Name              string      `json:"name"`
	Schema            interface{} `json:"schema"`
	ShowStepName      *bool       `json:"showStepName,omitempty"`
	ShowStepSubtitle  *bool       `json:"showStepSubtitle,omitempty"`
	ShowStepper       *bool       `json:"showStepper,omitempty"`
	ShowStepperLabels *bool       `json:"showStepperLabels,omitempty"`
	StepID            *string     `json:"stepId,omitempty"`
	SubTitle          *string     `json:"subTitle,omitempty"`
	Title             *string     `json:"title,omitempty"`
	Uischema          interface{} `json:"uischema"`
}

func (o *JourneyV2Steps) GetHideNextButton() *bool {
	if o == nil {
		return nil
	}
	return o.HideNextButton
}

func (o *JourneyV2Steps) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *JourneyV2Steps) GetSchema() interface{} {
	if o == nil {
		return nil
	}
	return o.Schema
}

func (o *JourneyV2Steps) GetShowStepName() *bool {
	if o == nil {
		return nil
	}
	return o.ShowStepName
}

func (o *JourneyV2Steps) GetShowStepSubtitle() *bool {
	if o == nil {
		return nil
	}
	return o.ShowStepSubtitle
}

func (o *JourneyV2Steps) GetShowStepper() *bool {
	if o == nil {
		return nil
	}
	return o.ShowStepper
}

func (o *JourneyV2Steps) GetShowStepperLabels() *bool {
	if o == nil {
		return nil
	}
	return o.ShowStepperLabels
}

func (o *JourneyV2Steps) GetStepID() *string {
	if o == nil {
		return nil
	}
	return o.StepID
}

func (o *JourneyV2Steps) GetSubTitle() *string {
	if o == nil {
		return nil
	}
	return o.SubTitle
}

func (o *JourneyV2Steps) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *JourneyV2Steps) GetUischema() interface{} {
	if o == nil {
		return nil
	}
	return o.Uischema
}

type JourneyV2 struct {
	BrandID   *string            `json:"brandId,omitempty"`
	Design    *JourneyV2Design   `json:"design,omitempty"`
	JourneyID *string            `json:"journeyId,omitempty"`
	Logics    []JourneyV2Logics  `json:"logics,omitempty"`
	Name      string             `json:"name"`
	Rules     []JourneyV2Rules   `json:"rules,omitempty"`
	Settings  *JourneyV2Settings `json:"settings,omitempty"`
	Steps     []JourneyV2Steps   `json:"steps"`
}

func (o *JourneyV2) GetBrandID() *string {
	if o == nil {
		return nil
	}
	return o.BrandID
}

func (o *JourneyV2) GetDesign() *JourneyV2Design {
	if o == nil {
		return nil
	}
	return o.Design
}

func (o *JourneyV2) GetJourneyID() *string {
	if o == nil {
		return nil
	}
	return o.JourneyID
}

func (o *JourneyV2) GetLogics() []JourneyV2Logics {
	if o == nil {
		return nil
	}
	return o.Logics
}

func (o *JourneyV2) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *JourneyV2) GetRules() []JourneyV2Rules {
	if o == nil {
		return nil
	}
	return o.Rules
}

func (o *JourneyV2) GetSettings() *JourneyV2Settings {
	if o == nil {
		return nil
	}
	return o.Settings
}

func (o *JourneyV2) GetSteps() []JourneyV2Steps {
	if o == nil {
		return []JourneyV2Steps{}
	}
	return o.Steps
}
