package shared

type JourneyResponseDesign struct {
	LogoURL *string                `json:"logoUrl,omitempty"`
	Theme   map[string]interface{} `json:"theme"`
}

type JourneyResponseLogics struct {
	Actions         []string `json:"actions"`
	AutoGeneratedID *string  `json:"autoGeneratedId,omitempty"`
	Conditions      []string `json:"conditions"`
}

type JourneyResponseRulesSourceTypeEnum string

const (
	JourneyResponseRulesSourceTypeEnumJourney JourneyResponseRulesSourceTypeEnum = "journey"
	JourneyResponseRulesSourceTypeEnumStep    JourneyResponseRulesSourceTypeEnum = "step"
	JourneyResponseRulesSourceTypeEnumBlock   JourneyResponseRulesSourceTypeEnum = "block"
)

type JourneyResponseRulesTypeEnum string

const (
	JourneyResponseRulesTypeEnumInject        JourneyResponseRulesTypeEnum = "inject"
	JourneyResponseRulesTypeEnumInjectWithKey JourneyResponseRulesTypeEnum = "injectWithKey"
)

type JourneyResponseRules struct {
	Source     string                             `json:"source"`
	SourceType JourneyResponseRulesSourceTypeEnum `json:"sourceType"`
	Target     string                             `json:"target"`
	Type       JourneyResponseRulesTypeEnum       `json:"type"`
}

type JourneyResponseSettingsEmbedOptionsButtonAlignEnum string

const (
	JourneyResponseSettingsEmbedOptionsButtonAlignEnumLeft   JourneyResponseSettingsEmbedOptionsButtonAlignEnum = "left"
	JourneyResponseSettingsEmbedOptionsButtonAlignEnumCenter JourneyResponseSettingsEmbedOptionsButtonAlignEnum = "center"
	JourneyResponseSettingsEmbedOptionsButtonAlignEnumRight  JourneyResponseSettingsEmbedOptionsButtonAlignEnum = "right"
)

type JourneyResponseSettingsEmbedOptionsButton struct {
	Align *JourneyResponseSettingsEmbedOptionsButtonAlignEnum `json:"align,omitempty"`
	Text  *string                                             `json:"text,omitempty"`
}

type JourneyResponseSettingsEmbedOptionsLangEnum string

const (
	JourneyResponseSettingsEmbedOptionsLangEnumDe JourneyResponseSettingsEmbedOptionsLangEnum = "de"
	JourneyResponseSettingsEmbedOptionsLangEnumEn JourneyResponseSettingsEmbedOptionsLangEnum = "en"
	JourneyResponseSettingsEmbedOptionsLangEnumFr JourneyResponseSettingsEmbedOptionsLangEnum = "fr"
)

type JourneyResponseSettingsEmbedOptionsModeEnum string

const (
	JourneyResponseSettingsEmbedOptionsModeEnumFullScreen JourneyResponseSettingsEmbedOptionsModeEnum = "full-screen"
	JourneyResponseSettingsEmbedOptionsModeEnumInline     JourneyResponseSettingsEmbedOptionsModeEnum = "inline"
)

type JourneyResponseSettingsEmbedOptions struct {
	Button      *JourneyResponseSettingsEmbedOptionsButton   `json:"button,omitempty"`
	Lang        *JourneyResponseSettingsEmbedOptionsLangEnum `json:"lang,omitempty"`
	Mode        *JourneyResponseSettingsEmbedOptionsModeEnum `json:"mode,omitempty"`
	ScrollToTop *bool                                        `json:"scrollToTop,omitempty"`
	TopBar      *bool                                        `json:"topBar,omitempty"`
	Width       *string                                      `json:"width,omitempty"`
}

type JourneyResponseSettingsRuntimeEntitiesEnum string

const (
	JourneyResponseSettingsRuntimeEntitiesEnumOrder       JourneyResponseSettingsRuntimeEntitiesEnum = "ORDER"
	JourneyResponseSettingsRuntimeEntitiesEnumOpportunity JourneyResponseSettingsRuntimeEntitiesEnum = "OPPORTUNITY"
)

type JourneyResponseSettings struct {
	Description          *string                                      `json:"description,omitempty"`
	DesignID             string                                       `json:"designId"`
	EmbedOptions         *JourneyResponseSettingsEmbedOptions         `json:"embedOptions,omitempty"`
	EntityID             *string                                      `json:"entityId,omitempty"`
	EntityTags           []string                                     `json:"entityTags,omitempty"`
	MappingsAutomationID *string                                      `json:"mappingsAutomationId,omitempty"`
	OrganizationSettings map[string]bool                              `json:"organizationSettings,omitempty"`
	PublicToken          *string                                      `json:"publicToken,omitempty"`
	RuntimeEntities      []JourneyResponseSettingsRuntimeEntitiesEnum `json:"runtimeEntities,omitempty"`
	SafeModeAutomation   *bool                                        `json:"safeModeAutomation,omitempty"`
	TargetedCustomer     *string                                      `json:"targetedCustomer,omitempty"`
	TemplateID           *string                                      `json:"templateId,omitempty"`
}

type JourneyResponseSteps struct {
	HideNextButton    *bool       `json:"hideNextButton,omitempty"`
	Name              string      `json:"name"`
	Schema            interface{} `json:"schema"`
	ShowStepName      *bool       `json:"showStepName,omitempty"`
	ShowStepSubtitle  *bool       `json:"showStepSubtitle,omitempty"`
	ShowStepper       *bool       `json:"showStepper,omitempty"`
	ShowStepperLabels *bool       `json:"showStepperLabels,omitempty"`
	StepID            *string     `json:"stepId,omitempty"`
	SubTitle          *string     `json:"subTitle,omitempty"`
	Title             *string     `json:"title,omitempty"`
	Uischema          interface{} `json:"uischema"`
}

type JourneyResponse struct {
	BrandID        string                   `json:"brandId"`
	CreatedBy      *string                  `json:"createdBy,omitempty"`
	Design         *JourneyResponseDesign   `json:"design,omitempty"`
	JourneyID      *string                  `json:"journeyId,omitempty"`
	Logics         []JourneyResponseLogics  `json:"logics,omitempty"`
	Name           string                   `json:"name"`
	OrganizationID string                   `json:"organizationId"`
	Rules          []JourneyResponseRules   `json:"rules,omitempty"`
	Settings       *JourneyResponseSettings `json:"settings,omitempty"`
	Steps          []JourneyResponseSteps   `json:"steps"`
}
