// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ButtonOption - A single button option data
type ButtonOption struct {
	// The label of the button
	Label *string `json:"label,omitempty"`
	// The value of the button
	Value *string `json:"value,omitempty"`
}

func (o *ButtonOption) GetLabel() *string {
	if o == nil {
		return nil
	}
	return o.Label
}

func (o *ButtonOption) GetValue() *string {
	if o == nil {
		return nil
	}
	return o.Value
}
