// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type OutputDocument struct {
	// Generated document filename for DOCX
	Filename *string      `json:"filename,omitempty"`
	S3ref    *S3Reference `json:"s3ref,omitempty"`
}

func (o *OutputDocument) GetFilename() *string {
	if o == nil {
		return nil
	}
	return o.Filename
}

func (o *OutputDocument) GetS3ref() *S3Reference {
	if o == nil {
		return nil
	}
	return o.S3ref
}

type DocxOutput struct {
	OutputDocument *OutputDocument `json:"output_document,omitempty"`
	// Pre-signed S3 GET URL for DOCX preview
	PreviewURL *string `json:"preview_url,omitempty"`
}

func (d *DocxOutput) GetOutputDocument() *OutputDocument {
	if d == nil {
		return nil
	}
	return d.OutputDocument
}

func (d *DocxOutput) GetPreviewURL() *string {
	if d == nil {
		return nil
	}
	return d.PreviewURL
}

// JobStatus - Status of the job
type JobStatus string

const (
	JobStatusStarted    JobStatus = "STARTED"
	JobStatusProcessing JobStatus = "PROCESSING"
	JobStatusSuccess    JobStatus = "SUCCESS"
	JobStatusFailed     JobStatus = "FAILED"
)

func (e JobStatus) ToPointer() *JobStatus {
	return &e
}
func (e *JobStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "STARTED":
		fallthrough
	case "PROCESSING":
		fallthrough
	case "SUCCESS":
		fallthrough
	case "FAILED":
		*e = JobStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JobStatus: %v", v)
	}
}

type GenerateDocumentResponseOutputDocument struct {
	// Generated document filename for PDF
	Filename *string      `json:"filename,omitempty"`
	S3ref    *S3Reference `json:"s3ref,omitempty"`
}

func (g *GenerateDocumentResponseOutputDocument) GetFilename() *string {
	if g == nil {
		return nil
	}
	return g.Filename
}

func (g *GenerateDocumentResponseOutputDocument) GetS3ref() *S3Reference {
	if g == nil {
		return nil
	}
	return g.S3ref
}

type PdfOutput struct {
	OutputDocument *GenerateDocumentResponseOutputDocument `json:"output_document,omitempty"`
	// Pre-signed S3 GET URL for PDF preview
	PreviewURL *string `json:"preview_url,omitempty"`
}

func (p *PdfOutput) GetOutputDocument() *GenerateDocumentResponseOutputDocument {
	if p == nil {
		return nil
	}
	return p.OutputDocument
}

func (p *PdfOutput) GetPreviewURL() *string {
	if p == nil {
		return nil
	}
	return p.PreviewURL
}

// VariablePayload - List of variables and its corresponding replaced values from the document template
type VariablePayload struct {
	AdditionalProperties *string `json:"additionalProperties,omitempty"`
}

func (v *VariablePayload) GetAdditionalProperties() *string {
	if v == nil {
		return nil
	}
	return v.AdditionalProperties
}

type GenerateDocumentResponse struct {
	DocxOutput *DocxOutput `json:"docx_output,omitempty"`
	JobID      *string     `json:"job_id,omitempty"`
	// Status of the job
	JobStatus *JobStatus `json:"job_status,omitempty"`
	// A message explaining the progress
	Message   *string    `json:"message,omitempty"`
	PdfOutput *PdfOutput `json:"pdf_output,omitempty"`
	// Template Settings for document generation
	TemplateSettings *TemplateSettings `json:"template_settings,omitempty"`
	// List of variables and its corresponding replaced values from the document template
	VariablePayload *VariablePayload `json:"variable_payload,omitempty"`
}

func (g *GenerateDocumentResponse) GetDocxOutput() *DocxOutput {
	if g == nil {
		return nil
	}
	return g.DocxOutput
}

func (g *GenerateDocumentResponse) GetJobID() *string {
	if g == nil {
		return nil
	}
	return g.JobID
}

func (g *GenerateDocumentResponse) GetJobStatus() *JobStatus {
	if g == nil {
		return nil
	}
	return g.JobStatus
}

func (g *GenerateDocumentResponse) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GenerateDocumentResponse) GetPdfOutput() *PdfOutput {
	if g == nil {
		return nil
	}
	return g.PdfOutput
}

func (g *GenerateDocumentResponse) GetTemplateSettings() *TemplateSettings {
	if g == nil {
		return nil
	}
	return g.TemplateSettings
}

func (g *GenerateDocumentResponse) GetVariablePayload() *VariablePayload {
	if g == nil {
		return nil
	}
	return g.VariablePayload
}
