// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ContextData - Custom values for variables in the template. Takes the higher precedence than others.
type ContextData struct {
	AdditionalProperties *string `json:"additionalProperties,omitempty"`
}

func (o *ContextData) GetAdditionalProperties() *string {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

// TemplateDocument - Input template document
type TemplateDocument struct {
	// Document original filename
	Filename *string      `json:"filename,omitempty"`
	S3ref    *S3Reference `json:"s3ref,omitempty"`
}

func (o *TemplateDocument) GetFilename() *string {
	if o == nil {
		return nil
	}
	return o.Filename
}

func (o *TemplateDocument) GetS3ref() *S3Reference {
	if o == nil {
		return nil
	}
	return o.S3ref
}

type GenerateDocumentRequest struct {
	// Custom values for variables in the template. Takes the higher precedence than others.
	ContextData ContextData `json:"context_data"`
	// Language code for the document
	Language *string `json:"language,omitempty"`
	// Input template document
	TemplateDocument TemplateDocument `json:"template_document"`
}

func (o *GenerateDocumentRequest) GetContextData() ContextData {
	if o == nil {
		return ContextData{}
	}
	return o.ContextData
}

func (o *GenerateDocumentRequest) GetLanguage() *string {
	if o == nil {
		return nil
	}
	return o.Language
}

func (o *GenerateDocumentRequest) GetTemplateDocument() TemplateDocument {
	if o == nil {
		return TemplateDocument{}
	}
	return o.TemplateDocument
}
