// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ContextData - Custom values for variables in the template. Takes the higher precedence than others.
type ContextData struct {
	AdditionalProperties *string `json:"additionalProperties,omitempty"`
}

func (o *ContextData) GetAdditionalProperties() *string {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

type GenerateDocumentRequest struct {
	// Custom values for variables in the template. Takes the higher precedence than others.
	ContextData ContextData `json:"context_data"`
	// Entity id for the template being used
	FileID string `json:"file_id"`
	// Language code for the document
	Language *string `json:"language,omitempty"`
}

func (o *GenerateDocumentRequest) GetContextData() ContextData {
	if o == nil {
		return ContextData{}
	}
	return o.ContextData
}

func (o *GenerateDocumentRequest) GetFileID() string {
	if o == nil {
		return ""
	}
	return o.FileID
}

func (o *GenerateDocumentRequest) GetLanguage() *string {
	if o == nil {
		return nil
	}
	return o.Language
}
