// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type GetSettingsForJourney struct {
	// The canary flag controls update frequency of epilot application: when true, customers receive continuous updates; when false, they only get updates with new version releases.
	Canary *bool `json:"canary,omitempty"`
	// ID of an organization in epilot platform
	OrganizationID *string `json:"organizationId,omitempty"`
	// When set to false, third-party cookies and resources should be completely disabled to comply with GDPR regulations.
	ThirdPartyCookies *bool `json:"thirdPartyCookies,omitempty"`
}

func (g *GetSettingsForJourney) GetCanary() *bool {
	if g == nil {
		return nil
	}
	return g.Canary
}

func (g *GetSettingsForJourney) GetOrganizationID() *string {
	if g == nil {
		return nil
	}
	return g.OrganizationID
}

func (g *GetSettingsForJourney) GetThirdPartyCookies() *bool {
	if g == nil {
		return nil
	}
	return g.ThirdPartyCookies
}
