// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type GetSettingsForJourney struct {
	// The canary flag controls update frequency of epilot application: when true, customers receive continuous updates; when false, they only get updates with new version releases.
	Canary *bool `json:"canary,omitempty"`
	// ID of an organization in epilot platform
	OrganizationID *string `json:"organizationId,omitempty"`
}

func (o *GetSettingsForJourney) GetCanary() *bool {
	if o == nil {
		return nil
	}
	return o.Canary
}

func (o *GetSettingsForJourney) GetOrganizationID() *string {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}
