// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type Severity string

const (
	SeverityCritical Severity = "critical"
	SeverityHigh     Severity = "high"
	SeverityMedium   Severity = "medium"
	SeverityLow      Severity = "low"
)

func (e Severity) ToPointer() *Severity {
	return &e
}
func (e *Severity) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "critical":
		fallthrough
	case "high":
		fallthrough
	case "medium":
		fallthrough
	case "low":
		*e = Severity(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Severity: %v", v)
	}
}

type Details struct {
	// Number of issues found
	Count *int64 `json:"count,omitempty"`
	// Detailed error message
	Message *string `json:"message,omitempty"`
	// Validation pattern that failed
	Pattern  *string   `json:"pattern,omitempty"`
	Severity *Severity `json:"severity,omitempty"`
}

func (d *Details) GetCount() *int64 {
	if d == nil {
		return nil
	}
	return d.Count
}

func (d *Details) GetMessage() *string {
	if d == nil {
		return nil
	}
	return d.Message
}

func (d *Details) GetPattern() *string {
	if d == nil {
		return nil
	}
	return d.Pattern
}

func (d *Details) GetSeverity() *Severity {
	if d == nil {
		return nil
	}
	return d.Severity
}

type JourneyValidationError struct {
	// Detailed validation errors for each pattern that failed
	Details []Details `json:"details"`
	// Error type identifier
	Error string `json:"error"`
	// High-level error message
	Message string `json:"message"`
}

func (j *JourneyValidationError) GetDetails() []Details {
	if j == nil {
		return []Details{}
	}
	return j.Details
}

func (j *JourneyValidationError) GetError() string {
	if j == nil {
		return ""
	}
	return j.Error
}

func (j *JourneyValidationError) GetMessage() string {
	if j == nil {
		return ""
	}
	return j.Message
}
