// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Price struct {
}

type JourneyProductsResponse struct {
	ID               *string `json:"_id,omitempty"`
	Org              *string `json:"_org,omitempty"`
	Schema           *string `json:"_schema,omitempty"`
	Title            *string `json:"_title,omitempty"`
	Code             *string `json:"code,omitempty"`
	Description      *string `json:"description,omitempty"`
	Feature          []any   `json:"feature,omitempty"`
	LegalFootnote    *string `json:"legal_footnote,omitempty"`
	Name             *string `json:"name,omitempty"`
	Price            *Price  `json:"price,omitempty"`
	ProductDownloads []any   `json:"product_downloads,omitempty"`
	ProductImages    []any   `json:"product_images,omitempty"`
	Type             *string `json:"type,omitempty"`
}

func (j *JourneyProductsResponse) GetID() *string {
	if j == nil {
		return nil
	}
	return j.ID
}

func (j *JourneyProductsResponse) GetOrg() *string {
	if j == nil {
		return nil
	}
	return j.Org
}

func (j *JourneyProductsResponse) GetSchema() *string {
	if j == nil {
		return nil
	}
	return j.Schema
}

func (j *JourneyProductsResponse) GetTitle() *string {
	if j == nil {
		return nil
	}
	return j.Title
}

func (j *JourneyProductsResponse) GetCode() *string {
	if j == nil {
		return nil
	}
	return j.Code
}

func (j *JourneyProductsResponse) GetDescription() *string {
	if j == nil {
		return nil
	}
	return j.Description
}

func (j *JourneyProductsResponse) GetFeature() []any {
	if j == nil {
		return nil
	}
	return j.Feature
}

func (j *JourneyProductsResponse) GetLegalFootnote() *string {
	if j == nil {
		return nil
	}
	return j.LegalFootnote
}

func (j *JourneyProductsResponse) GetName() *string {
	if j == nil {
		return nil
	}
	return j.Name
}

func (j *JourneyProductsResponse) GetPrice() *Price {
	if j == nil {
		return nil
	}
	return j.Price
}

func (j *JourneyProductsResponse) GetProductDownloads() []any {
	if j == nil {
		return nil
	}
	return j.ProductDownloads
}

func (j *JourneyProductsResponse) GetProductImages() []any {
	if j == nil {
		return nil
	}
	return j.ProductImages
}

func (j *JourneyProductsResponse) GetType() *string {
	if j == nil {
		return nil
	}
	return j.Type
}
