// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type JourneyCreationRequestV2ContextSchema struct {
	// Unique identifier for the context schema item
	ID *string `json:"id,omitempty"`
	// Indicates if a value is expected to be provided
	IsRequired *bool `json:"isRequired,omitempty"`
	// Expected key to be received in the context
	ParamKey string `json:"paramKey"`
	// If type is not text, we can instruct the journey to fetch the entity id we receive as value
	ShouldLoadEntity *bool `json:"shouldLoadEntity,omitempty"`
	// Type of the parameter. It could be either an entity slug, or a text
	Type string `json:"type"`
}

func (j *JourneyCreationRequestV2ContextSchema) GetID() *string {
	if j == nil {
		return nil
	}
	return j.ID
}

func (j *JourneyCreationRequestV2ContextSchema) GetIsRequired() *bool {
	if j == nil {
		return nil
	}
	return j.IsRequired
}

func (j *JourneyCreationRequestV2ContextSchema) GetParamKey() string {
	if j == nil {
		return ""
	}
	return j.ParamKey
}

func (j *JourneyCreationRequestV2ContextSchema) GetShouldLoadEntity() *bool {
	if j == nil {
		return nil
	}
	return j.ShouldLoadEntity
}

func (j *JourneyCreationRequestV2ContextSchema) GetType() string {
	if j == nil {
		return ""
	}
	return j.Type
}

type JourneyCreationRequestV2DesignTokens struct {
}

type JourneyCreationRequestV2Design struct {
	DesignTokens *JourneyCreationRequestV2DesignTokens `json:"designTokens,omitempty"`
	LogoURL      *string                               `json:"logoUrl,omitempty"`
	Theme        map[string]any                        `json:"theme,omitempty"`
}

func (j *JourneyCreationRequestV2Design) GetDesignTokens() *JourneyCreationRequestV2DesignTokens {
	if j == nil {
		return nil
	}
	return j.DesignTokens
}

func (j *JourneyCreationRequestV2Design) GetLogoURL() *string {
	if j == nil {
		return nil
	}
	return j.LogoURL
}

func (j *JourneyCreationRequestV2Design) GetTheme() map[string]any {
	if j == nil {
		return nil
	}
	return j.Theme
}

type JourneyCreationRequestV2SourceType string

const (
	JourneyCreationRequestV2SourceTypeJourney JourneyCreationRequestV2SourceType = "journey"
	JourneyCreationRequestV2SourceTypeStep    JourneyCreationRequestV2SourceType = "step"
	JourneyCreationRequestV2SourceTypeBlock   JourneyCreationRequestV2SourceType = "block"
)

func (e JourneyCreationRequestV2SourceType) ToPointer() *JourneyCreationRequestV2SourceType {
	return &e
}
func (e *JourneyCreationRequestV2SourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "journey":
		fallthrough
	case "step":
		fallthrough
	case "block":
		*e = JourneyCreationRequestV2SourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JourneyCreationRequestV2SourceType: %v", v)
	}
}

type JourneyCreationRequestV2Type string

const (
	JourneyCreationRequestV2TypeInject        JourneyCreationRequestV2Type = "inject"
	JourneyCreationRequestV2TypeInjectWithKey JourneyCreationRequestV2Type = "injectWithKey"
)

func (e JourneyCreationRequestV2Type) ToPointer() *JourneyCreationRequestV2Type {
	return &e
}
func (e *JourneyCreationRequestV2Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "inject":
		fallthrough
	case "injectWithKey":
		*e = JourneyCreationRequestV2Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JourneyCreationRequestV2Type: %v", v)
	}
}

type JourneyCreationRequestV2Rules struct {
	Source     string                             `json:"source"`
	SourceType JourneyCreationRequestV2SourceType `json:"sourceType"`
	Target     string                             `json:"target"`
	Type       JourneyCreationRequestV2Type       `json:"type"`
}

func (j *JourneyCreationRequestV2Rules) GetSource() string {
	if j == nil {
		return ""
	}
	return j.Source
}

func (j *JourneyCreationRequestV2Rules) GetSourceType() JourneyCreationRequestV2SourceType {
	if j == nil {
		return JourneyCreationRequestV2SourceType("")
	}
	return j.SourceType
}

func (j *JourneyCreationRequestV2Rules) GetTarget() string {
	if j == nil {
		return ""
	}
	return j.Target
}

func (j *JourneyCreationRequestV2Rules) GetType() JourneyCreationRequestV2Type {
	if j == nil {
		return JourneyCreationRequestV2Type("")
	}
	return j.Type
}

type JourneyCreationRequestV2AccessMode string

const (
	JourneyCreationRequestV2AccessModePublic  JourneyCreationRequestV2AccessMode = "PUBLIC"
	JourneyCreationRequestV2AccessModePrivate JourneyCreationRequestV2AccessMode = "PRIVATE"
)

func (e JourneyCreationRequestV2AccessMode) ToPointer() *JourneyCreationRequestV2AccessMode {
	return &e
}
func (e *JourneyCreationRequestV2AccessMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PUBLIC":
		fallthrough
	case "PRIVATE":
		*e = JourneyCreationRequestV2AccessMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JourneyCreationRequestV2AccessMode: %v", v)
	}
}

type JourneyCreationRequestV2Align string

const (
	JourneyCreationRequestV2AlignLeft   JourneyCreationRequestV2Align = "left"
	JourneyCreationRequestV2AlignCenter JourneyCreationRequestV2Align = "center"
	JourneyCreationRequestV2AlignRight  JourneyCreationRequestV2Align = "right"
)

func (e JourneyCreationRequestV2Align) ToPointer() *JourneyCreationRequestV2Align {
	return &e
}
func (e *JourneyCreationRequestV2Align) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "left":
		fallthrough
	case "center":
		fallthrough
	case "right":
		*e = JourneyCreationRequestV2Align(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JourneyCreationRequestV2Align: %v", v)
	}
}

type JourneyCreationRequestV2Button struct {
	Align *JourneyCreationRequestV2Align `json:"align,omitempty"`
	Text  *string                        `json:"text,omitempty"`
}

func (j *JourneyCreationRequestV2Button) GetAlign() *JourneyCreationRequestV2Align {
	if j == nil {
		return nil
	}
	return j.Align
}

func (j *JourneyCreationRequestV2Button) GetText() *string {
	if j == nil {
		return nil
	}
	return j.Text
}

type JourneyCreationRequestV2Lang string

const (
	JourneyCreationRequestV2LangDe JourneyCreationRequestV2Lang = "de"
	JourneyCreationRequestV2LangEn JourneyCreationRequestV2Lang = "en"
	JourneyCreationRequestV2LangFr JourneyCreationRequestV2Lang = "fr"
)

func (e JourneyCreationRequestV2Lang) ToPointer() *JourneyCreationRequestV2Lang {
	return &e
}
func (e *JourneyCreationRequestV2Lang) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "de":
		fallthrough
	case "en":
		fallthrough
	case "fr":
		*e = JourneyCreationRequestV2Lang(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JourneyCreationRequestV2Lang: %v", v)
	}
}

type JourneyCreationRequestV2Mode string

const (
	JourneyCreationRequestV2ModeFullScreen JourneyCreationRequestV2Mode = "full-screen"
	JourneyCreationRequestV2ModeInline     JourneyCreationRequestV2Mode = "inline"
)

func (e JourneyCreationRequestV2Mode) ToPointer() *JourneyCreationRequestV2Mode {
	return &e
}
func (e *JourneyCreationRequestV2Mode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "full-screen":
		fallthrough
	case "inline":
		*e = JourneyCreationRequestV2Mode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JourneyCreationRequestV2Mode: %v", v)
	}
}

type JourneyCreationRequestV2EmbedOptions struct {
	Button      *JourneyCreationRequestV2Button `json:"button,omitempty"`
	Lang        *JourneyCreationRequestV2Lang   `json:"lang,omitempty"`
	Mode        *JourneyCreationRequestV2Mode   `json:"mode,omitempty"`
	ScrollToTop *bool                           `json:"scrollToTop,omitempty"`
	TopBar      *bool                           `json:"topBar,omitempty"`
	Width       *string                         `json:"width,omitempty"`
}

func (j *JourneyCreationRequestV2EmbedOptions) GetButton() *JourneyCreationRequestV2Button {
	if j == nil {
		return nil
	}
	return j.Button
}

func (j *JourneyCreationRequestV2EmbedOptions) GetLang() *JourneyCreationRequestV2Lang {
	if j == nil {
		return nil
	}
	return j.Lang
}

func (j *JourneyCreationRequestV2EmbedOptions) GetMode() *JourneyCreationRequestV2Mode {
	if j == nil {
		return nil
	}
	return j.Mode
}

func (j *JourneyCreationRequestV2EmbedOptions) GetScrollToTop() *bool {
	if j == nil {
		return nil
	}
	return j.ScrollToTop
}

func (j *JourneyCreationRequestV2EmbedOptions) GetTopBar() *bool {
	if j == nil {
		return nil
	}
	return j.TopBar
}

func (j *JourneyCreationRequestV2EmbedOptions) GetWidth() *string {
	if j == nil {
		return nil
	}
	return j.Width
}

type JourneyCreationRequestV2RuntimeEntities string

const (
	JourneyCreationRequestV2RuntimeEntitiesOrder       JourneyCreationRequestV2RuntimeEntities = "ORDER"
	JourneyCreationRequestV2RuntimeEntitiesOpportunity JourneyCreationRequestV2RuntimeEntities = "OPPORTUNITY"
)

func (e JourneyCreationRequestV2RuntimeEntities) ToPointer() *JourneyCreationRequestV2RuntimeEntities {
	return &e
}
func (e *JourneyCreationRequestV2RuntimeEntities) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ORDER":
		fallthrough
	case "OPPORTUNITY":
		*e = JourneyCreationRequestV2RuntimeEntities(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JourneyCreationRequestV2RuntimeEntities: %v", v)
	}
}

type JourneyCreationRequestV2Settings struct {
	AccessMode *JourneyCreationRequestV2AccessMode `json:"accessMode,omitempty"`
	// Country code for address format (e.g. DE, AT, CH, LU)
	AddressSuggestionsCountryCode *string `json:"addressSuggestionsCountryCode,omitempty"`
	// Whether address auto-complete is enabled
	AddressSuggestionsEnableAutoComplete *bool `json:"addressSuggestionsEnableAutoComplete,omitempty"`
	// Whether free text input is allowed when auto-complete is on
	AddressSuggestionsEnableFreeText *bool   `json:"addressSuggestionsEnableFreeText,omitempty"`
	AddressSuggestionsFileID         *string `json:"addressSuggestionsFileId,omitempty"`
	// @deprecated Use addressSuggestionsFileId instead
	AddressSuggestionsFileURL *string `json:"addressSuggestionsFileUrl,omitempty"`
	// Sources for address auto-complete (e.g. deutschePostService, customAddressesFile)
	AddressSuggestionsSource []string                              `json:"addressSuggestionsSource,omitempty"`
	Description              *string                               `json:"description,omitempty"`
	DesignID                 *string                               `json:"designId,omitempty"`
	EmbedOptions             *JourneyCreationRequestV2EmbedOptions `json:"embedOptions,omitempty"`
	// If true, the journey shows an icon to toggle dark mode
	EnableDarkMode       *bool                                     `json:"enableDarkMode,omitempty"`
	EntityID             *string                                   `json:"entityId,omitempty"`
	EntityTags           []string                                  `json:"entityTags,omitempty"`
	FilePurposes         []string                                  `json:"filePurposes,omitempty"`
	IsActive             *bool                                     `json:"isActive,omitempty"`
	MappingsAutomationID *string                                   `json:"mappingsAutomationId,omitempty"`
	PublicToken          *string                                   `json:"publicToken,omitempty"`
	RuntimeEntities      []JourneyCreationRequestV2RuntimeEntities `json:"runtimeEntities,omitempty"`
	SafeModeAutomation   *bool                                     `json:"safeModeAutomation,omitempty"`
	TargetedCustomer     *string                                   `json:"targetedCustomer,omitempty"`
	TemplateID           *string                                   `json:"templateId,omitempty"`
	// If false, third-party cookies are disabled to comply with GDPR regulations without asking for consent.
	ThirdPartyCookies *bool `json:"thirdPartyCookies,omitempty"`
	// This property is deprecated and will be removed in a future version
	UseNewDesign *bool `json:"useNewDesign,omitempty"`
}

func (j *JourneyCreationRequestV2Settings) GetAccessMode() *JourneyCreationRequestV2AccessMode {
	if j == nil {
		return nil
	}
	return j.AccessMode
}

func (j *JourneyCreationRequestV2Settings) GetAddressSuggestionsCountryCode() *string {
	if j == nil {
		return nil
	}
	return j.AddressSuggestionsCountryCode
}

func (j *JourneyCreationRequestV2Settings) GetAddressSuggestionsEnableAutoComplete() *bool {
	if j == nil {
		return nil
	}
	return j.AddressSuggestionsEnableAutoComplete
}

func (j *JourneyCreationRequestV2Settings) GetAddressSuggestionsEnableFreeText() *bool {
	if j == nil {
		return nil
	}
	return j.AddressSuggestionsEnableFreeText
}

func (j *JourneyCreationRequestV2Settings) GetAddressSuggestionsFileID() *string {
	if j == nil {
		return nil
	}
	return j.AddressSuggestionsFileID
}

func (j *JourneyCreationRequestV2Settings) GetAddressSuggestionsFileURL() *string {
	if j == nil {
		return nil
	}
	return j.AddressSuggestionsFileURL
}

func (j *JourneyCreationRequestV2Settings) GetAddressSuggestionsSource() []string {
	if j == nil {
		return nil
	}
	return j.AddressSuggestionsSource
}

func (j *JourneyCreationRequestV2Settings) GetDescription() *string {
	if j == nil {
		return nil
	}
	return j.Description
}

func (j *JourneyCreationRequestV2Settings) GetDesignID() *string {
	if j == nil {
		return nil
	}
	return j.DesignID
}

func (j *JourneyCreationRequestV2Settings) GetEmbedOptions() *JourneyCreationRequestV2EmbedOptions {
	if j == nil {
		return nil
	}
	return j.EmbedOptions
}

func (j *JourneyCreationRequestV2Settings) GetEnableDarkMode() *bool {
	if j == nil {
		return nil
	}
	return j.EnableDarkMode
}

func (j *JourneyCreationRequestV2Settings) GetEntityID() *string {
	if j == nil {
		return nil
	}
	return j.EntityID
}

func (j *JourneyCreationRequestV2Settings) GetEntityTags() []string {
	if j == nil {
		return nil
	}
	return j.EntityTags
}

func (j *JourneyCreationRequestV2Settings) GetFilePurposes() []string {
	if j == nil {
		return nil
	}
	return j.FilePurposes
}

func (j *JourneyCreationRequestV2Settings) GetIsActive() *bool {
	if j == nil {
		return nil
	}
	return j.IsActive
}

func (j *JourneyCreationRequestV2Settings) GetMappingsAutomationID() *string {
	if j == nil {
		return nil
	}
	return j.MappingsAutomationID
}

func (j *JourneyCreationRequestV2Settings) GetPublicToken() *string {
	if j == nil {
		return nil
	}
	return j.PublicToken
}

func (j *JourneyCreationRequestV2Settings) GetRuntimeEntities() []JourneyCreationRequestV2RuntimeEntities {
	if j == nil {
		return nil
	}
	return j.RuntimeEntities
}

func (j *JourneyCreationRequestV2Settings) GetSafeModeAutomation() *bool {
	if j == nil {
		return nil
	}
	return j.SafeModeAutomation
}

func (j *JourneyCreationRequestV2Settings) GetTargetedCustomer() *string {
	if j == nil {
		return nil
	}
	return j.TargetedCustomer
}

func (j *JourneyCreationRequestV2Settings) GetTemplateID() *string {
	if j == nil {
		return nil
	}
	return j.TemplateID
}

func (j *JourneyCreationRequestV2Settings) GetThirdPartyCookies() *bool {
	if j == nil {
		return nil
	}
	return j.ThirdPartyCookies
}

func (j *JourneyCreationRequestV2Settings) GetUseNewDesign() *bool {
	if j == nil {
		return nil
	}
	return j.UseNewDesign
}

type JourneyCreationRequestV2 struct {
	// Manifest/Blueprint ID used to create/update the entity
	Manifest      []string                                `json:"_manifest,omitempty"`
	BrandID       *string                                 `json:"brandId,omitempty"`
	ContextSchema []JourneyCreationRequestV2ContextSchema `json:"contextSchema,omitempty"`
	Design        *JourneyCreationRequestV2Design         `json:"design,omitempty"`
	JourneyID     *string                                 `json:"journeyId,omitempty"`
	// Journey Template
	JourneyType *string `json:"journey_type,omitempty"`
	Logics      any     `json:"logics,omitempty"`
	LogicsV4    any     `json:"logicsV4,omitempty"`
	Name        string  `json:"name"`
	// If true, journey is displayed in read-only mode
	Protected *bool `json:"protected,omitempty"`
	// Whitelist of paths that remain editable when the journey is protected. Supports wildcard patterns (e.g. steps/*/blocks/**).
	ProtectedEditable []string                          `json:"protectedEditable,omitempty"`
	Rules             []JourneyCreationRequestV2Rules   `json:"rules,omitempty"`
	Settings          *JourneyCreationRequestV2Settings `json:"settings,omitempty"`
	Steps             any                               `json:"steps"`
	ValidationRules   any                               `json:"validationRules,omitempty"`
}

func (j *JourneyCreationRequestV2) GetManifest() []string {
	if j == nil {
		return nil
	}
	return j.Manifest
}

func (j *JourneyCreationRequestV2) GetBrandID() *string {
	if j == nil {
		return nil
	}
	return j.BrandID
}

func (j *JourneyCreationRequestV2) GetContextSchema() []JourneyCreationRequestV2ContextSchema {
	if j == nil {
		return nil
	}
	return j.ContextSchema
}

func (j *JourneyCreationRequestV2) GetDesign() *JourneyCreationRequestV2Design {
	if j == nil {
		return nil
	}
	return j.Design
}

func (j *JourneyCreationRequestV2) GetJourneyID() *string {
	if j == nil {
		return nil
	}
	return j.JourneyID
}

func (j *JourneyCreationRequestV2) GetJourneyType() *string {
	if j == nil {
		return nil
	}
	return j.JourneyType
}

func (j *JourneyCreationRequestV2) GetLogics() any {
	if j == nil {
		return nil
	}
	return j.Logics
}

func (j *JourneyCreationRequestV2) GetLogicsV4() any {
	if j == nil {
		return nil
	}
	return j.LogicsV4
}

func (j *JourneyCreationRequestV2) GetName() string {
	if j == nil {
		return ""
	}
	return j.Name
}

func (j *JourneyCreationRequestV2) GetProtected() *bool {
	if j == nil {
		return nil
	}
	return j.Protected
}

func (j *JourneyCreationRequestV2) GetProtectedEditable() []string {
	if j == nil {
		return nil
	}
	return j.ProtectedEditable
}

func (j *JourneyCreationRequestV2) GetRules() []JourneyCreationRequestV2Rules {
	if j == nil {
		return nil
	}
	return j.Rules
}

func (j *JourneyCreationRequestV2) GetSettings() *JourneyCreationRequestV2Settings {
	if j == nil {
		return nil
	}
	return j.Settings
}

func (j *JourneyCreationRequestV2) GetSteps() any {
	if j == nil {
		return nil
	}
	return j.Steps
}

func (j *JourneyCreationRequestV2) GetValidationRules() any {
	if j == nil {
		return nil
	}
	return j.ValidationRules
}
