// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-journey/internal/sdk/internal/utils"
)

type ContextSchema struct {
	// Unique identifier for the context schema item
	ID *string `json:"id,omitempty"`
	// Indicates if a value is expected to be provided
	IsRequired *bool `json:"isRequired,omitempty"`
	// Expected key to be received in the context
	ParamKey string `json:"paramKey"`
	// If type is not text, we can instruct the journey to fetch the entity id we receive as value
	ShouldLoadEntity *bool `json:"shouldLoadEntity,omitempty"`
	// Type of the parameter. It could be either an entity slug, or a text
	Type string `json:"type"`
}

func (c *ContextSchema) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *ContextSchema) GetIsRequired() *bool {
	if c == nil {
		return nil
	}
	return c.IsRequired
}

func (c *ContextSchema) GetParamKey() string {
	if c == nil {
		return ""
	}
	return c.ParamKey
}

func (c *ContextSchema) GetShouldLoadEntity() *bool {
	if c == nil {
		return nil
	}
	return c.ShouldLoadEntity
}

func (c *ContextSchema) GetType() string {
	if c == nil {
		return ""
	}
	return c.Type
}

type DesignTokens struct {
}

type Design struct {
	DesignTokens *DesignTokens  `json:"designTokens,omitempty"`
	LogoURL      *string        `json:"logoUrl,omitempty"`
	Theme        map[string]any `json:"theme,omitempty"`
}

func (d *Design) GetDesignTokens() *DesignTokens {
	if d == nil {
		return nil
	}
	return d.DesignTokens
}

func (d *Design) GetLogoURL() *string {
	if d == nil {
		return nil
	}
	return d.LogoURL
}

func (d *Design) GetTheme() map[string]any {
	if d == nil {
		return nil
	}
	return d.Theme
}

type Logics struct {
	Actions         []string `json:"actions"`
	AutoGeneratedID *string  `json:"autoGeneratedId,omitempty"`
	Conditions      []string `json:"conditions"`
}

func (l *Logics) GetActions() []string {
	if l == nil {
		return []string{}
	}
	return l.Actions
}

func (l *Logics) GetAutoGeneratedID() *string {
	if l == nil {
		return nil
	}
	return l.AutoGeneratedID
}

func (l *Logics) GetConditions() []string {
	if l == nil {
		return []string{}
	}
	return l.Conditions
}

type SourceType string

const (
	SourceTypeJourney SourceType = "journey"
	SourceTypeStep    SourceType = "step"
	SourceTypeBlock   SourceType = "block"
)

func (e SourceType) ToPointer() *SourceType {
	return &e
}
func (e *SourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "journey":
		fallthrough
	case "step":
		fallthrough
	case "block":
		*e = SourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SourceType: %v", v)
	}
}

type Type string

const (
	TypeInject        Type = "inject"
	TypeInjectWithKey Type = "injectWithKey"
)

func (e Type) ToPointer() *Type {
	return &e
}
func (e *Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "inject":
		fallthrough
	case "injectWithKey":
		*e = Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Type: %v", v)
	}
}

type Rules struct {
	Source     string     `json:"source"`
	SourceType SourceType `json:"sourceType"`
	Target     string     `json:"target"`
	Type       Type       `json:"type"`
}

func (r *Rules) GetSource() string {
	if r == nil {
		return ""
	}
	return r.Source
}

func (r *Rules) GetSourceType() SourceType {
	if r == nil {
		return SourceType("")
	}
	return r.SourceType
}

func (r *Rules) GetTarget() string {
	if r == nil {
		return ""
	}
	return r.Target
}

func (r *Rules) GetType() Type {
	if r == nil {
		return Type("")
	}
	return r.Type
}

type AccessMode string

const (
	AccessModePublic  AccessMode = "PUBLIC"
	AccessModePrivate AccessMode = "PRIVATE"
)

func (e AccessMode) ToPointer() *AccessMode {
	return &e
}
func (e *AccessMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PUBLIC":
		fallthrough
	case "PRIVATE":
		*e = AccessMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AccessMode: %v", v)
	}
}

type Align string

const (
	AlignLeft   Align = "left"
	AlignCenter Align = "center"
	AlignRight  Align = "right"
)

func (e Align) ToPointer() *Align {
	return &e
}
func (e *Align) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "left":
		fallthrough
	case "center":
		fallthrough
	case "right":
		*e = Align(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Align: %v", v)
	}
}

type Button struct {
	Align *Align  `json:"align,omitempty"`
	Text  *string `json:"text,omitempty"`
}

func (b *Button) GetAlign() *Align {
	if b == nil {
		return nil
	}
	return b.Align
}

func (b *Button) GetText() *string {
	if b == nil {
		return nil
	}
	return b.Text
}

type Lang string

const (
	LangDe Lang = "de"
	LangEn Lang = "en"
	LangFr Lang = "fr"
)

func (e Lang) ToPointer() *Lang {
	return &e
}
func (e *Lang) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "de":
		fallthrough
	case "en":
		fallthrough
	case "fr":
		*e = Lang(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Lang: %v", v)
	}
}

type Mode string

const (
	ModeFullScreen Mode = "full-screen"
	ModeInline     Mode = "inline"
)

func (e Mode) ToPointer() *Mode {
	return &e
}
func (e *Mode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "full-screen":
		fallthrough
	case "inline":
		*e = Mode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Mode: %v", v)
	}
}

type EmbedOptions struct {
	Button      *Button `json:"button,omitempty"`
	Lang        *Lang   `json:"lang,omitempty"`
	Mode        *Mode   `json:"mode,omitempty"`
	ScrollToTop *bool   `json:"scrollToTop,omitempty"`
	TopBar      *bool   `json:"topBar,omitempty"`
	Width       *string `json:"width,omitempty"`
}

func (e *EmbedOptions) GetButton() *Button {
	if e == nil {
		return nil
	}
	return e.Button
}

func (e *EmbedOptions) GetLang() *Lang {
	if e == nil {
		return nil
	}
	return e.Lang
}

func (e *EmbedOptions) GetMode() *Mode {
	if e == nil {
		return nil
	}
	return e.Mode
}

func (e *EmbedOptions) GetScrollToTop() *bool {
	if e == nil {
		return nil
	}
	return e.ScrollToTop
}

func (e *EmbedOptions) GetTopBar() *bool {
	if e == nil {
		return nil
	}
	return e.TopBar
}

func (e *EmbedOptions) GetWidth() *string {
	if e == nil {
		return nil
	}
	return e.Width
}

type RuntimeEntities string

const (
	RuntimeEntitiesOrder       RuntimeEntities = "ORDER"
	RuntimeEntitiesOpportunity RuntimeEntities = "OPPORTUNITY"
)

func (e RuntimeEntities) ToPointer() *RuntimeEntities {
	return &e
}
func (e *RuntimeEntities) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ORDER":
		fallthrough
	case "OPPORTUNITY":
		*e = RuntimeEntities(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RuntimeEntities: %v", v)
	}
}

type SavingMode string

const (
	SavingModeAuto   SavingMode = "auto"
	SavingModeLocal  SavingMode = "local"
	SavingModeRemote SavingMode = "remote"
	SavingModeNone   SavingMode = "none"
)

func (e SavingMode) ToPointer() *SavingMode {
	return &e
}
func (e *SavingMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "auto":
		fallthrough
	case "local":
		fallthrough
	case "remote":
		fallthrough
	case "none":
		*e = SavingMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SavingMode: %v", v)
	}
}

type SavingProgress struct {
	SavingMode       *SavingMode `json:"savingMode,omitempty"`
	SupportedVersion *float64    `json:"supportedVersion,omitempty"`
}

func (s *SavingProgress) GetSavingMode() *SavingMode {
	if s == nil {
		return nil
	}
	return s.SavingMode
}

func (s *SavingProgress) GetSupportedVersion() *float64 {
	if s == nil {
		return nil
	}
	return s.SupportedVersion
}

type Settings struct {
	AccessMode *AccessMode `json:"accessMode,omitempty"`
	// Country code for address format (e.g. DE, AT, CH, LU)
	AddressSuggestionsCountryCode *string `json:"addressSuggestionsCountryCode,omitempty"`
	// Whether address auto-complete is enabled
	AddressSuggestionsEnableAutoComplete *bool `json:"addressSuggestionsEnableAutoComplete,omitempty"`
	// Whether free text input is allowed when auto-complete is on
	AddressSuggestionsEnableFreeText *bool   `json:"addressSuggestionsEnableFreeText,omitempty"`
	AddressSuggestionsFileID         *string `json:"addressSuggestionsFileId,omitempty"`
	// @deprecated Use addressSuggestionsFileId instead
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	AddressSuggestionsFileURL *string `json:"addressSuggestionsFileUrl,omitempty"`
	// Sources for address auto-complete (e.g. deutschePostService, customAddressesFile)
	AddressSuggestionsSource []string `json:"addressSuggestionsSource,omitempty"`
	// DEPRECATED - This API will return hardcoded value of false. Please note that this field is internal to epilot and should not be used by external clients. If you wish to get the canary flag, please use the /v1/journey/{id}/settings API.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Canary       *bool         `json:"canary,omitempty"`
	Description  *string       `json:"description,omitempty"`
	DesignID     string        `json:"designId"`
	EmbedOptions *EmbedOptions `json:"embedOptions,omitempty"`
	// If true, the journey shows an icon to toggle dark mode
	EnableDarkMode       *bool             `json:"enableDarkMode,omitempty"`
	EntityID             *string           `json:"entityId,omitempty"`
	EntityTags           []string          `json:"entityTags,omitempty"`
	FilePurposes         []string          `json:"filePurposes,omitempty"`
	IsActive             *bool             `json:"isActive,omitempty"`
	IsPublished          *bool             `json:"isPublished,omitempty"`
	MappingsAutomationID *string           `json:"mappingsAutomationId,omitempty"`
	OrganizationSettings map[string]bool   `json:"organizationSettings,omitempty"`
	PublicToken          *string           `json:"publicToken,omitempty"`
	RuntimeEntities      []RuntimeEntities `json:"runtimeEntities,omitempty"`
	SafeModeAutomation   *bool             `json:"safeModeAutomation,omitempty"`
	SavingProgress       *SavingProgress   `json:"savingProgress,omitempty"`
	Status               *string           `json:"status,omitempty"`
	TargetedCustomer     *string           `json:"targetedCustomer,omitempty"`
	TemplateID           *string           `json:"templateId,omitempty"`
	// If false, third-party cookies are disabled to comply with GDPR regulations without asking for consent.
	ThirdPartyCookies *bool `json:"thirdPartyCookies,omitempty"`
	// If true, some journey input labels are in Austrian format
	UseAustrianLabels *bool `json:"useAustrianLabels,omitempty"`
	// This property is deprecated and will be removed in a future version
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	UseNewDesign *bool `json:"useNewDesign,omitempty"`
}

func (s *Settings) GetAccessMode() *AccessMode {
	if s == nil {
		return nil
	}
	return s.AccessMode
}

func (s *Settings) GetAddressSuggestionsCountryCode() *string {
	if s == nil {
		return nil
	}
	return s.AddressSuggestionsCountryCode
}

func (s *Settings) GetAddressSuggestionsEnableAutoComplete() *bool {
	if s == nil {
		return nil
	}
	return s.AddressSuggestionsEnableAutoComplete
}

func (s *Settings) GetAddressSuggestionsEnableFreeText() *bool {
	if s == nil {
		return nil
	}
	return s.AddressSuggestionsEnableFreeText
}

func (s *Settings) GetAddressSuggestionsFileID() *string {
	if s == nil {
		return nil
	}
	return s.AddressSuggestionsFileID
}

func (s *Settings) GetAddressSuggestionsFileURL() *string {
	if s == nil {
		return nil
	}
	return s.AddressSuggestionsFileURL
}

func (s *Settings) GetAddressSuggestionsSource() []string {
	if s == nil {
		return nil
	}
	return s.AddressSuggestionsSource
}

func (s *Settings) GetCanary() *bool {
	if s == nil {
		return nil
	}
	return s.Canary
}

func (s *Settings) GetDescription() *string {
	if s == nil {
		return nil
	}
	return s.Description
}

func (s *Settings) GetDesignID() string {
	if s == nil {
		return ""
	}
	return s.DesignID
}

func (s *Settings) GetEmbedOptions() *EmbedOptions {
	if s == nil {
		return nil
	}
	return s.EmbedOptions
}

func (s *Settings) GetEnableDarkMode() *bool {
	if s == nil {
		return nil
	}
	return s.EnableDarkMode
}

func (s *Settings) GetEntityID() *string {
	if s == nil {
		return nil
	}
	return s.EntityID
}

func (s *Settings) GetEntityTags() []string {
	if s == nil {
		return nil
	}
	return s.EntityTags
}

func (s *Settings) GetFilePurposes() []string {
	if s == nil {
		return nil
	}
	return s.FilePurposes
}

func (s *Settings) GetIsActive() *bool {
	if s == nil {
		return nil
	}
	return s.IsActive
}

func (s *Settings) GetIsPublished() *bool {
	if s == nil {
		return nil
	}
	return s.IsPublished
}

func (s *Settings) GetMappingsAutomationID() *string {
	if s == nil {
		return nil
	}
	return s.MappingsAutomationID
}

func (s *Settings) GetOrganizationSettings() map[string]bool {
	if s == nil {
		return nil
	}
	return s.OrganizationSettings
}

func (s *Settings) GetPublicToken() *string {
	if s == nil {
		return nil
	}
	return s.PublicToken
}

func (s *Settings) GetRuntimeEntities() []RuntimeEntities {
	if s == nil {
		return nil
	}
	return s.RuntimeEntities
}

func (s *Settings) GetSafeModeAutomation() *bool {
	if s == nil {
		return nil
	}
	return s.SafeModeAutomation
}

func (s *Settings) GetSavingProgress() *SavingProgress {
	if s == nil {
		return nil
	}
	return s.SavingProgress
}

func (s *Settings) GetStatus() *string {
	if s == nil {
		return nil
	}
	return s.Status
}

func (s *Settings) GetTargetedCustomer() *string {
	if s == nil {
		return nil
	}
	return s.TargetedCustomer
}

func (s *Settings) GetTemplateID() *string {
	if s == nil {
		return nil
	}
	return s.TemplateID
}

func (s *Settings) GetThirdPartyCookies() *bool {
	if s == nil {
		return nil
	}
	return s.ThirdPartyCookies
}

func (s *Settings) GetUseAustrianLabels() *bool {
	if s == nil {
		return nil
	}
	return s.UseAustrianLabels
}

func (s *Settings) GetUseNewDesign() *bool {
	if s == nil {
		return nil
	}
	return s.UseNewDesign
}

type MaxWidth string

const (
	MaxWidthSmall      MaxWidth = "small"
	MaxWidthMedium     MaxWidth = "medium"
	MaxWidthLarge      MaxWidth = "large"
	MaxWidthExtraLarge MaxWidth = "extra large"
)

func (e MaxWidth) ToPointer() *MaxWidth {
	return &e
}
func (e *MaxWidth) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "small":
		fallthrough
	case "medium":
		fallthrough
	case "large":
		fallthrough
	case "extra large":
		*e = MaxWidth(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MaxWidth: %v", v)
	}
}

type Steps struct {
	HideNextButton    *bool     `json:"hideNextButton,omitempty"`
	MaxWidth          *MaxWidth `json:"maxWidth,omitempty"`
	Name              string    `json:"name"`
	Schema            any       `json:"schema"`
	ShowStepName      *bool     `json:"showStepName,omitempty"`
	ShowStepSubtitle  *bool     `json:"showStepSubtitle,omitempty"`
	ShowStepper       *bool     `json:"showStepper,omitempty"`
	ShowStepperLabels *bool     `json:"showStepperLabels,omitempty"`
	StepID            *string   `json:"stepId,omitempty"`
	SubTitle          *string   `json:"subTitle,omitempty"`
	Title             *string   `json:"title,omitempty"`
	Uischema          any       `json:"uischema"`
}

func (s *Steps) GetHideNextButton() *bool {
	if s == nil {
		return nil
	}
	return s.HideNextButton
}

func (s *Steps) GetMaxWidth() *MaxWidth {
	if s == nil {
		return nil
	}
	return s.MaxWidth
}

func (s *Steps) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *Steps) GetSchema() any {
	if s == nil {
		return nil
	}
	return s.Schema
}

func (s *Steps) GetShowStepName() *bool {
	if s == nil {
		return nil
	}
	return s.ShowStepName
}

func (s *Steps) GetShowStepSubtitle() *bool {
	if s == nil {
		return nil
	}
	return s.ShowStepSubtitle
}

func (s *Steps) GetShowStepper() *bool {
	if s == nil {
		return nil
	}
	return s.ShowStepper
}

func (s *Steps) GetShowStepperLabels() *bool {
	if s == nil {
		return nil
	}
	return s.ShowStepperLabels
}

func (s *Steps) GetStepID() *string {
	if s == nil {
		return nil
	}
	return s.StepID
}

func (s *Steps) GetSubTitle() *string {
	if s == nil {
		return nil
	}
	return s.SubTitle
}

func (s *Steps) GetTitle() *string {
	if s == nil {
		return nil
	}
	return s.Title
}

func (s *Steps) GetUischema() any {
	if s == nil {
		return nil
	}
	return s.Uischema
}

type Journey struct {
	AdditionalProperties any `additionalProperties:"true" json:"-"`
	// If passed with value of null, the API won't modify the lastModifiedAt field on updating the journey
	LastModifiedAt *string `json:"__lastModifiedAt,omitempty"`
	// Manifest/Blueprint ID used to create/update the entity
	Manifest      []string        `json:"_manifest,omitempty"`
	BrandID       *string         `json:"brandId,omitempty"`
	ContextSchema []ContextSchema `json:"contextSchema,omitempty"`
	CreatedAt     string          `json:"createdAt"`
	CreatedBy     *string         `json:"createdBy,omitempty"`
	DeletedAt     *string         `json:"deletedAt,omitempty"`
	Design        *Design         `json:"design,omitempty"`
	FeatureFlags  map[string]any  `json:"featureFlags,omitempty"`
	JourneyID     *string         `json:"journeyId,omitempty"`
	// Journey Template
	JourneyType     *string  `json:"journey_type,omitempty"`
	LastModifiedAt1 string   `json:"lastModifiedAt"`
	Logics          []Logics `json:"logics,omitempty"`
	LogicsV4        any      `json:"logicsV4,omitempty"`
	Name            string   `json:"name"`
	OrganizationID  string   `json:"organizationId"`
	// If true, journey is displayed in read-only mode
	Protected *bool `json:"protected,omitempty"`
	// Whitelist of paths that remain editable when the journey is protected. Supports wildcard patterns (e.g. steps/*/blocks/**).
	ProtectedEditable []string  `json:"protectedEditable,omitempty"`
	Revisions         float64   `json:"revisions"`
	Rules             []Rules   `json:"rules,omitempty"`
	Settings          *Settings `json:"settings,omitempty"`
	Steps             []Steps   `json:"steps"`
	UpdatedBy         *string   `json:"updatedBy,omitempty"`
	ValidationRules   any       `json:"validationRules,omitempty"`
	Version           float64   `json:"version"`
}

func (j Journey) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(j, "", false)
}

func (j *Journey) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &j, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (j *Journey) GetAdditionalProperties() any {
	if j == nil {
		return nil
	}
	return j.AdditionalProperties
}

func (j *Journey) GetLastModifiedAt() *string {
	if j == nil {
		return nil
	}
	return j.LastModifiedAt
}

func (j *Journey) GetManifest() []string {
	if j == nil {
		return nil
	}
	return j.Manifest
}

func (j *Journey) GetBrandID() *string {
	if j == nil {
		return nil
	}
	return j.BrandID
}

func (j *Journey) GetContextSchema() []ContextSchema {
	if j == nil {
		return nil
	}
	return j.ContextSchema
}

func (j *Journey) GetCreatedAt() string {
	if j == nil {
		return ""
	}
	return j.CreatedAt
}

func (j *Journey) GetCreatedBy() *string {
	if j == nil {
		return nil
	}
	return j.CreatedBy
}

func (j *Journey) GetDeletedAt() *string {
	if j == nil {
		return nil
	}
	return j.DeletedAt
}

func (j *Journey) GetDesign() *Design {
	if j == nil {
		return nil
	}
	return j.Design
}

func (j *Journey) GetFeatureFlags() map[string]any {
	if j == nil {
		return nil
	}
	return j.FeatureFlags
}

func (j *Journey) GetJourneyID() *string {
	if j == nil {
		return nil
	}
	return j.JourneyID
}

func (j *Journey) GetJourneyType() *string {
	if j == nil {
		return nil
	}
	return j.JourneyType
}

func (j *Journey) GetLastModifiedAt1() string {
	if j == nil {
		return ""
	}
	return j.LastModifiedAt1
}

func (j *Journey) GetLogics() []Logics {
	if j == nil {
		return nil
	}
	return j.Logics
}

func (j *Journey) GetLogicsV4() any {
	if j == nil {
		return nil
	}
	return j.LogicsV4
}

func (j *Journey) GetName() string {
	if j == nil {
		return ""
	}
	return j.Name
}

func (j *Journey) GetOrganizationID() string {
	if j == nil {
		return ""
	}
	return j.OrganizationID
}

func (j *Journey) GetProtected() *bool {
	if j == nil {
		return nil
	}
	return j.Protected
}

func (j *Journey) GetProtectedEditable() []string {
	if j == nil {
		return nil
	}
	return j.ProtectedEditable
}

func (j *Journey) GetRevisions() float64 {
	if j == nil {
		return 0.0
	}
	return j.Revisions
}

func (j *Journey) GetRules() []Rules {
	if j == nil {
		return nil
	}
	return j.Rules
}

func (j *Journey) GetSettings() *Settings {
	if j == nil {
		return nil
	}
	return j.Settings
}

func (j *Journey) GetSteps() []Steps {
	if j == nil {
		return []Steps{}
	}
	return j.Steps
}

func (j *Journey) GetUpdatedBy() *string {
	if j == nil {
		return nil
	}
	return j.UpdatedBy
}

func (j *Journey) GetValidationRules() any {
	if j == nil {
		return nil
	}
	return j.ValidationRules
}

func (j *Journey) GetVersion() float64 {
	if j == nil {
		return 0.0
	}
	return j.Version
}
