// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type JourneyResponse struct {
	CreatedJourney *Journey `json:"createdJourney,omitempty"`
}

func (j *JourneyResponse) GetCreatedJourney() *Journey {
	if j == nil {
		return nil
	}
	return j.CreatedJourney
}
