// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-journey/internal/sdk/internal/utils"
)

type JourneyCreationRequestContextSchema struct {
	// Unique identifier for the context schema item
	ID *string `json:"id,omitempty"`
	// Indicates if a value is expected to be provided
	IsRequired *bool `json:"isRequired,omitempty"`
	// Expected key to be received in the context
	ParamKey string `json:"paramKey"`
	// If type is not text, we can instruct the journey to fetch the entity id we receive as value
	ShouldLoadEntity *bool `json:"shouldLoadEntity,omitempty"`
	// Type of the parameter. It could be either an entity slug, or a text
	Type string `json:"type"`
}

func (j *JourneyCreationRequestContextSchema) GetID() *string {
	if j == nil {
		return nil
	}
	return j.ID
}

func (j *JourneyCreationRequestContextSchema) GetIsRequired() *bool {
	if j == nil {
		return nil
	}
	return j.IsRequired
}

func (j *JourneyCreationRequestContextSchema) GetParamKey() string {
	if j == nil {
		return ""
	}
	return j.ParamKey
}

func (j *JourneyCreationRequestContextSchema) GetShouldLoadEntity() *bool {
	if j == nil {
		return nil
	}
	return j.ShouldLoadEntity
}

func (j *JourneyCreationRequestContextSchema) GetType() string {
	if j == nil {
		return ""
	}
	return j.Type
}

type JourneyCreationRequestDesignTokens struct {
}

type JourneyCreationRequestDesign struct {
	DesignTokens *JourneyCreationRequestDesignTokens `json:"designTokens,omitempty"`
	LogoURL      *string                             `json:"logoUrl,omitempty"`
	Theme        map[string]any                      `json:"theme,omitempty"`
}

func (j *JourneyCreationRequestDesign) GetDesignTokens() *JourneyCreationRequestDesignTokens {
	if j == nil {
		return nil
	}
	return j.DesignTokens
}

func (j *JourneyCreationRequestDesign) GetLogoURL() *string {
	if j == nil {
		return nil
	}
	return j.LogoURL
}

func (j *JourneyCreationRequestDesign) GetTheme() map[string]any {
	if j == nil {
		return nil
	}
	return j.Theme
}

type JourneyCreationRequestLogics struct {
	Actions         []string `json:"actions"`
	AutoGeneratedID *string  `json:"autoGeneratedId,omitempty"`
	Conditions      []string `json:"conditions"`
}

func (j *JourneyCreationRequestLogics) GetActions() []string {
	if j == nil {
		return []string{}
	}
	return j.Actions
}

func (j *JourneyCreationRequestLogics) GetAutoGeneratedID() *string {
	if j == nil {
		return nil
	}
	return j.AutoGeneratedID
}

func (j *JourneyCreationRequestLogics) GetConditions() []string {
	if j == nil {
		return []string{}
	}
	return j.Conditions
}

type JourneyCreationRequestSourceType string

const (
	JourneyCreationRequestSourceTypeJourney JourneyCreationRequestSourceType = "journey"
	JourneyCreationRequestSourceTypeStep    JourneyCreationRequestSourceType = "step"
	JourneyCreationRequestSourceTypeBlock   JourneyCreationRequestSourceType = "block"
)

func (e JourneyCreationRequestSourceType) ToPointer() *JourneyCreationRequestSourceType {
	return &e
}
func (e *JourneyCreationRequestSourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "journey":
		fallthrough
	case "step":
		fallthrough
	case "block":
		*e = JourneyCreationRequestSourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JourneyCreationRequestSourceType: %v", v)
	}
}

type JourneyCreationRequestType string

const (
	JourneyCreationRequestTypeInject        JourneyCreationRequestType = "inject"
	JourneyCreationRequestTypeInjectWithKey JourneyCreationRequestType = "injectWithKey"
)

func (e JourneyCreationRequestType) ToPointer() *JourneyCreationRequestType {
	return &e
}
func (e *JourneyCreationRequestType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "inject":
		fallthrough
	case "injectWithKey":
		*e = JourneyCreationRequestType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JourneyCreationRequestType: %v", v)
	}
}

type JourneyCreationRequestRules struct {
	Source     string                           `json:"source"`
	SourceType JourneyCreationRequestSourceType `json:"sourceType"`
	Target     string                           `json:"target"`
	Type       JourneyCreationRequestType       `json:"type"`
}

func (j *JourneyCreationRequestRules) GetSource() string {
	if j == nil {
		return ""
	}
	return j.Source
}

func (j *JourneyCreationRequestRules) GetSourceType() JourneyCreationRequestSourceType {
	if j == nil {
		return JourneyCreationRequestSourceType("")
	}
	return j.SourceType
}

func (j *JourneyCreationRequestRules) GetTarget() string {
	if j == nil {
		return ""
	}
	return j.Target
}

func (j *JourneyCreationRequestRules) GetType() JourneyCreationRequestType {
	if j == nil {
		return JourneyCreationRequestType("")
	}
	return j.Type
}

type JourneyCreationRequestAccessMode string

const (
	JourneyCreationRequestAccessModePublic  JourneyCreationRequestAccessMode = "PUBLIC"
	JourneyCreationRequestAccessModePrivate JourneyCreationRequestAccessMode = "PRIVATE"
)

func (e JourneyCreationRequestAccessMode) ToPointer() *JourneyCreationRequestAccessMode {
	return &e
}
func (e *JourneyCreationRequestAccessMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PUBLIC":
		fallthrough
	case "PRIVATE":
		*e = JourneyCreationRequestAccessMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JourneyCreationRequestAccessMode: %v", v)
	}
}

type JourneyCreationRequestAlign string

const (
	JourneyCreationRequestAlignLeft   JourneyCreationRequestAlign = "left"
	JourneyCreationRequestAlignCenter JourneyCreationRequestAlign = "center"
	JourneyCreationRequestAlignRight  JourneyCreationRequestAlign = "right"
)

func (e JourneyCreationRequestAlign) ToPointer() *JourneyCreationRequestAlign {
	return &e
}
func (e *JourneyCreationRequestAlign) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "left":
		fallthrough
	case "center":
		fallthrough
	case "right":
		*e = JourneyCreationRequestAlign(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JourneyCreationRequestAlign: %v", v)
	}
}

type JourneyCreationRequestButton struct {
	Align *JourneyCreationRequestAlign `json:"align,omitempty"`
	Text  *string                      `json:"text,omitempty"`
}

func (j *JourneyCreationRequestButton) GetAlign() *JourneyCreationRequestAlign {
	if j == nil {
		return nil
	}
	return j.Align
}

func (j *JourneyCreationRequestButton) GetText() *string {
	if j == nil {
		return nil
	}
	return j.Text
}

type JourneyCreationRequestLang string

const (
	JourneyCreationRequestLangDe JourneyCreationRequestLang = "de"
	JourneyCreationRequestLangEn JourneyCreationRequestLang = "en"
	JourneyCreationRequestLangFr JourneyCreationRequestLang = "fr"
)

func (e JourneyCreationRequestLang) ToPointer() *JourneyCreationRequestLang {
	return &e
}
func (e *JourneyCreationRequestLang) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "de":
		fallthrough
	case "en":
		fallthrough
	case "fr":
		*e = JourneyCreationRequestLang(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JourneyCreationRequestLang: %v", v)
	}
}

type JourneyCreationRequestMode string

const (
	JourneyCreationRequestModeFullScreen JourneyCreationRequestMode = "full-screen"
	JourneyCreationRequestModeInline     JourneyCreationRequestMode = "inline"
)

func (e JourneyCreationRequestMode) ToPointer() *JourneyCreationRequestMode {
	return &e
}
func (e *JourneyCreationRequestMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "full-screen":
		fallthrough
	case "inline":
		*e = JourneyCreationRequestMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JourneyCreationRequestMode: %v", v)
	}
}

type JourneyCreationRequestEmbedOptions struct {
	Button      *JourneyCreationRequestButton `json:"button,omitempty"`
	Lang        *JourneyCreationRequestLang   `json:"lang,omitempty"`
	Mode        *JourneyCreationRequestMode   `json:"mode,omitempty"`
	ScrollToTop *bool                         `json:"scrollToTop,omitempty"`
	TopBar      *bool                         `json:"topBar,omitempty"`
	Width       *string                       `json:"width,omitempty"`
}

func (j *JourneyCreationRequestEmbedOptions) GetButton() *JourneyCreationRequestButton {
	if j == nil {
		return nil
	}
	return j.Button
}

func (j *JourneyCreationRequestEmbedOptions) GetLang() *JourneyCreationRequestLang {
	if j == nil {
		return nil
	}
	return j.Lang
}

func (j *JourneyCreationRequestEmbedOptions) GetMode() *JourneyCreationRequestMode {
	if j == nil {
		return nil
	}
	return j.Mode
}

func (j *JourneyCreationRequestEmbedOptions) GetScrollToTop() *bool {
	if j == nil {
		return nil
	}
	return j.ScrollToTop
}

func (j *JourneyCreationRequestEmbedOptions) GetTopBar() *bool {
	if j == nil {
		return nil
	}
	return j.TopBar
}

func (j *JourneyCreationRequestEmbedOptions) GetWidth() *string {
	if j == nil {
		return nil
	}
	return j.Width
}

type JourneyCreationRequestRuntimeEntities string

const (
	JourneyCreationRequestRuntimeEntitiesOrder       JourneyCreationRequestRuntimeEntities = "ORDER"
	JourneyCreationRequestRuntimeEntitiesOpportunity JourneyCreationRequestRuntimeEntities = "OPPORTUNITY"
)

func (e JourneyCreationRequestRuntimeEntities) ToPointer() *JourneyCreationRequestRuntimeEntities {
	return &e
}
func (e *JourneyCreationRequestRuntimeEntities) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ORDER":
		fallthrough
	case "OPPORTUNITY":
		*e = JourneyCreationRequestRuntimeEntities(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JourneyCreationRequestRuntimeEntities: %v", v)
	}
}

type JourneyCreationRequestSavingMode string

const (
	JourneyCreationRequestSavingModeAuto   JourneyCreationRequestSavingMode = "auto"
	JourneyCreationRequestSavingModeLocal  JourneyCreationRequestSavingMode = "local"
	JourneyCreationRequestSavingModeRemote JourneyCreationRequestSavingMode = "remote"
	JourneyCreationRequestSavingModeNone   JourneyCreationRequestSavingMode = "none"
)

func (e JourneyCreationRequestSavingMode) ToPointer() *JourneyCreationRequestSavingMode {
	return &e
}
func (e *JourneyCreationRequestSavingMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "auto":
		fallthrough
	case "local":
		fallthrough
	case "remote":
		fallthrough
	case "none":
		*e = JourneyCreationRequestSavingMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JourneyCreationRequestSavingMode: %v", v)
	}
}

type JourneyCreationRequestSavingProgress struct {
	SavingMode       *JourneyCreationRequestSavingMode `json:"savingMode,omitempty"`
	SupportedVersion *float64                          `json:"supportedVersion,omitempty"`
}

func (j *JourneyCreationRequestSavingProgress) GetSavingMode() *JourneyCreationRequestSavingMode {
	if j == nil {
		return nil
	}
	return j.SavingMode
}

func (j *JourneyCreationRequestSavingProgress) GetSupportedVersion() *float64 {
	if j == nil {
		return nil
	}
	return j.SupportedVersion
}

type JourneyCreationRequestSettings struct {
	AccessMode *JourneyCreationRequestAccessMode `json:"accessMode,omitempty"`
	// Country code for address format (e.g. DE, AT, CH, LU)
	AddressSuggestionsCountryCode *string `json:"addressSuggestionsCountryCode,omitempty"`
	// Whether address auto-complete is enabled
	AddressSuggestionsEnableAutoComplete *bool `json:"addressSuggestionsEnableAutoComplete,omitempty"`
	// Whether free text input is allowed when auto-complete is on
	AddressSuggestionsEnableFreeText *bool   `json:"addressSuggestionsEnableFreeText,omitempty"`
	AddressSuggestionsFileID         *string `json:"addressSuggestionsFileId,omitempty"`
	// @deprecated Use addressSuggestionsFileId instead
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	AddressSuggestionsFileURL *string `json:"addressSuggestionsFileUrl,omitempty"`
	// Sources for address auto-complete (e.g. deutschePostService, customAddressesFile)
	AddressSuggestionsSource []string `json:"addressSuggestionsSource,omitempty"`
	// DEPRECATED - This API will return hardcoded value of false. Please note that this field is internal to epilot and should not be used by external clients. If you wish to get the canary flag, please use the /v1/journey/{id}/settings API.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Canary       *bool                               `json:"canary,omitempty"`
	Description  *string                             `json:"description,omitempty"`
	DesignID     string                              `json:"designId"`
	EmbedOptions *JourneyCreationRequestEmbedOptions `json:"embedOptions,omitempty"`
	// If true, the journey shows an icon to toggle dark mode
	EnableDarkMode       *bool                                   `json:"enableDarkMode,omitempty"`
	EntityID             *string                                 `json:"entityId,omitempty"`
	EntityTags           []string                                `json:"entityTags,omitempty"`
	FilePurposes         []string                                `json:"filePurposes,omitempty"`
	IsActive             *bool                                   `json:"isActive,omitempty"`
	IsPublished          *bool                                   `json:"isPublished,omitempty"`
	MappingsAutomationID *string                                 `json:"mappingsAutomationId,omitempty"`
	OrganizationSettings map[string]bool                         `json:"organizationSettings,omitempty"`
	PublicToken          *string                                 `json:"publicToken,omitempty"`
	RuntimeEntities      []JourneyCreationRequestRuntimeEntities `json:"runtimeEntities,omitempty"`
	SafeModeAutomation   *bool                                   `json:"safeModeAutomation,omitempty"`
	SavingProgress       *JourneyCreationRequestSavingProgress   `json:"savingProgress,omitempty"`
	Status               *string                                 `json:"status,omitempty"`
	TargetedCustomer     *string                                 `json:"targetedCustomer,omitempty"`
	TemplateID           *string                                 `json:"templateId,omitempty"`
	// If false, third-party cookies are disabled to comply with GDPR regulations without asking for consent.
	ThirdPartyCookies *bool `json:"thirdPartyCookies,omitempty"`
	// If true, some journey input labels are in Austrian format
	UseAustrianLabels *bool `json:"useAustrianLabels,omitempty"`
	// This property is deprecated and will be removed in a future version
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	UseNewDesign *bool `json:"useNewDesign,omitempty"`
}

func (j *JourneyCreationRequestSettings) GetAccessMode() *JourneyCreationRequestAccessMode {
	if j == nil {
		return nil
	}
	return j.AccessMode
}

func (j *JourneyCreationRequestSettings) GetAddressSuggestionsCountryCode() *string {
	if j == nil {
		return nil
	}
	return j.AddressSuggestionsCountryCode
}

func (j *JourneyCreationRequestSettings) GetAddressSuggestionsEnableAutoComplete() *bool {
	if j == nil {
		return nil
	}
	return j.AddressSuggestionsEnableAutoComplete
}

func (j *JourneyCreationRequestSettings) GetAddressSuggestionsEnableFreeText() *bool {
	if j == nil {
		return nil
	}
	return j.AddressSuggestionsEnableFreeText
}

func (j *JourneyCreationRequestSettings) GetAddressSuggestionsFileID() *string {
	if j == nil {
		return nil
	}
	return j.AddressSuggestionsFileID
}

func (j *JourneyCreationRequestSettings) GetAddressSuggestionsFileURL() *string {
	if j == nil {
		return nil
	}
	return j.AddressSuggestionsFileURL
}

func (j *JourneyCreationRequestSettings) GetAddressSuggestionsSource() []string {
	if j == nil {
		return nil
	}
	return j.AddressSuggestionsSource
}

func (j *JourneyCreationRequestSettings) GetCanary() *bool {
	if j == nil {
		return nil
	}
	return j.Canary
}

func (j *JourneyCreationRequestSettings) GetDescription() *string {
	if j == nil {
		return nil
	}
	return j.Description
}

func (j *JourneyCreationRequestSettings) GetDesignID() string {
	if j == nil {
		return ""
	}
	return j.DesignID
}

func (j *JourneyCreationRequestSettings) GetEmbedOptions() *JourneyCreationRequestEmbedOptions {
	if j == nil {
		return nil
	}
	return j.EmbedOptions
}

func (j *JourneyCreationRequestSettings) GetEnableDarkMode() *bool {
	if j == nil {
		return nil
	}
	return j.EnableDarkMode
}

func (j *JourneyCreationRequestSettings) GetEntityID() *string {
	if j == nil {
		return nil
	}
	return j.EntityID
}

func (j *JourneyCreationRequestSettings) GetEntityTags() []string {
	if j == nil {
		return nil
	}
	return j.EntityTags
}

func (j *JourneyCreationRequestSettings) GetFilePurposes() []string {
	if j == nil {
		return nil
	}
	return j.FilePurposes
}

func (j *JourneyCreationRequestSettings) GetIsActive() *bool {
	if j == nil {
		return nil
	}
	return j.IsActive
}

func (j *JourneyCreationRequestSettings) GetIsPublished() *bool {
	if j == nil {
		return nil
	}
	return j.IsPublished
}

func (j *JourneyCreationRequestSettings) GetMappingsAutomationID() *string {
	if j == nil {
		return nil
	}
	return j.MappingsAutomationID
}

func (j *JourneyCreationRequestSettings) GetOrganizationSettings() map[string]bool {
	if j == nil {
		return nil
	}
	return j.OrganizationSettings
}

func (j *JourneyCreationRequestSettings) GetPublicToken() *string {
	if j == nil {
		return nil
	}
	return j.PublicToken
}

func (j *JourneyCreationRequestSettings) GetRuntimeEntities() []JourneyCreationRequestRuntimeEntities {
	if j == nil {
		return nil
	}
	return j.RuntimeEntities
}

func (j *JourneyCreationRequestSettings) GetSafeModeAutomation() *bool {
	if j == nil {
		return nil
	}
	return j.SafeModeAutomation
}

func (j *JourneyCreationRequestSettings) GetSavingProgress() *JourneyCreationRequestSavingProgress {
	if j == nil {
		return nil
	}
	return j.SavingProgress
}

func (j *JourneyCreationRequestSettings) GetStatus() *string {
	if j == nil {
		return nil
	}
	return j.Status
}

func (j *JourneyCreationRequestSettings) GetTargetedCustomer() *string {
	if j == nil {
		return nil
	}
	return j.TargetedCustomer
}

func (j *JourneyCreationRequestSettings) GetTemplateID() *string {
	if j == nil {
		return nil
	}
	return j.TemplateID
}

func (j *JourneyCreationRequestSettings) GetThirdPartyCookies() *bool {
	if j == nil {
		return nil
	}
	return j.ThirdPartyCookies
}

func (j *JourneyCreationRequestSettings) GetUseAustrianLabels() *bool {
	if j == nil {
		return nil
	}
	return j.UseAustrianLabels
}

func (j *JourneyCreationRequestSettings) GetUseNewDesign() *bool {
	if j == nil {
		return nil
	}
	return j.UseNewDesign
}

type JourneyCreationRequestMaxWidth string

const (
	JourneyCreationRequestMaxWidthSmall      JourneyCreationRequestMaxWidth = "small"
	JourneyCreationRequestMaxWidthMedium     JourneyCreationRequestMaxWidth = "medium"
	JourneyCreationRequestMaxWidthLarge      JourneyCreationRequestMaxWidth = "large"
	JourneyCreationRequestMaxWidthExtraLarge JourneyCreationRequestMaxWidth = "extra large"
)

func (e JourneyCreationRequestMaxWidth) ToPointer() *JourneyCreationRequestMaxWidth {
	return &e
}
func (e *JourneyCreationRequestMaxWidth) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "small":
		fallthrough
	case "medium":
		fallthrough
	case "large":
		fallthrough
	case "extra large":
		*e = JourneyCreationRequestMaxWidth(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JourneyCreationRequestMaxWidth: %v", v)
	}
}

type JourneyCreationRequestSteps struct {
	HideNextButton    *bool                           `json:"hideNextButton,omitempty"`
	MaxWidth          *JourneyCreationRequestMaxWidth `json:"maxWidth,omitempty"`
	Name              string                          `json:"name"`
	Schema            any                             `json:"schema"`
	ShowStepName      *bool                           `json:"showStepName,omitempty"`
	ShowStepSubtitle  *bool                           `json:"showStepSubtitle,omitempty"`
	ShowStepper       *bool                           `json:"showStepper,omitempty"`
	ShowStepperLabels *bool                           `json:"showStepperLabels,omitempty"`
	StepID            *string                         `json:"stepId,omitempty"`
	SubTitle          *string                         `json:"subTitle,omitempty"`
	Title             *string                         `json:"title,omitempty"`
	Uischema          any                             `json:"uischema"`
}

func (j *JourneyCreationRequestSteps) GetHideNextButton() *bool {
	if j == nil {
		return nil
	}
	return j.HideNextButton
}

func (j *JourneyCreationRequestSteps) GetMaxWidth() *JourneyCreationRequestMaxWidth {
	if j == nil {
		return nil
	}
	return j.MaxWidth
}

func (j *JourneyCreationRequestSteps) GetName() string {
	if j == nil {
		return ""
	}
	return j.Name
}

func (j *JourneyCreationRequestSteps) GetSchema() any {
	if j == nil {
		return nil
	}
	return j.Schema
}

func (j *JourneyCreationRequestSteps) GetShowStepName() *bool {
	if j == nil {
		return nil
	}
	return j.ShowStepName
}

func (j *JourneyCreationRequestSteps) GetShowStepSubtitle() *bool {
	if j == nil {
		return nil
	}
	return j.ShowStepSubtitle
}

func (j *JourneyCreationRequestSteps) GetShowStepper() *bool {
	if j == nil {
		return nil
	}
	return j.ShowStepper
}

func (j *JourneyCreationRequestSteps) GetShowStepperLabels() *bool {
	if j == nil {
		return nil
	}
	return j.ShowStepperLabels
}

func (j *JourneyCreationRequestSteps) GetStepID() *string {
	if j == nil {
		return nil
	}
	return j.StepID
}

func (j *JourneyCreationRequestSteps) GetSubTitle() *string {
	if j == nil {
		return nil
	}
	return j.SubTitle
}

func (j *JourneyCreationRequestSteps) GetTitle() *string {
	if j == nil {
		return nil
	}
	return j.Title
}

func (j *JourneyCreationRequestSteps) GetUischema() any {
	if j == nil {
		return nil
	}
	return j.Uischema
}

type JourneyCreationRequest struct {
	AdditionalProperties any `additionalProperties:"true" json:"-"`
	// If passed with value of null, the API won't modify the lastModifiedAt field on updating the journey
	LastModifiedAt *string `json:"__lastModifiedAt,omitempty"`
	// Manifest/Blueprint ID used to create/update the entity
	Manifest      []string                              `json:"_manifest,omitempty"`
	BrandID       *string                               `json:"brandId,omitempty"`
	ContextSchema []JourneyCreationRequestContextSchema `json:"contextSchema,omitempty"`
	CreatedBy     *string                               `json:"createdBy,omitempty"`
	Design        *JourneyCreationRequestDesign         `json:"design,omitempty"`
	JourneyID     *string                               `json:"journeyId,omitempty"`
	// Journey Template
	JourneyType    *string                        `json:"journey_type,omitempty"`
	Logics         []JourneyCreationRequestLogics `json:"logics,omitempty"`
	LogicsV4       any                            `json:"logicsV4,omitempty"`
	Name           string                         `json:"name"`
	OrganizationID string                         `json:"organizationId"`
	// If true, journey is displayed in read-only mode
	Protected *bool `json:"protected,omitempty"`
	// Whitelist of paths that remain editable when the journey is protected. Supports wildcard patterns (e.g. steps/*/blocks/**).
	ProtectedEditable []string                        `json:"protectedEditable,omitempty"`
	Rules             []JourneyCreationRequestRules   `json:"rules,omitempty"`
	Settings          *JourneyCreationRequestSettings `json:"settings,omitempty"`
	Steps             []JourneyCreationRequestSteps   `json:"steps"`
	UpdatedBy         *string                         `json:"updatedBy,omitempty"`
	ValidationRules   any                             `json:"validationRules,omitempty"`
}

func (j JourneyCreationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(j, "", false)
}

func (j *JourneyCreationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &j, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (j *JourneyCreationRequest) GetAdditionalProperties() any {
	if j == nil {
		return nil
	}
	return j.AdditionalProperties
}

func (j *JourneyCreationRequest) GetLastModifiedAt() *string {
	if j == nil {
		return nil
	}
	return j.LastModifiedAt
}

func (j *JourneyCreationRequest) GetManifest() []string {
	if j == nil {
		return nil
	}
	return j.Manifest
}

func (j *JourneyCreationRequest) GetBrandID() *string {
	if j == nil {
		return nil
	}
	return j.BrandID
}

func (j *JourneyCreationRequest) GetContextSchema() []JourneyCreationRequestContextSchema {
	if j == nil {
		return nil
	}
	return j.ContextSchema
}

func (j *JourneyCreationRequest) GetCreatedBy() *string {
	if j == nil {
		return nil
	}
	return j.CreatedBy
}

func (j *JourneyCreationRequest) GetDesign() *JourneyCreationRequestDesign {
	if j == nil {
		return nil
	}
	return j.Design
}

func (j *JourneyCreationRequest) GetJourneyID() *string {
	if j == nil {
		return nil
	}
	return j.JourneyID
}

func (j *JourneyCreationRequest) GetJourneyType() *string {
	if j == nil {
		return nil
	}
	return j.JourneyType
}

func (j *JourneyCreationRequest) GetLogics() []JourneyCreationRequestLogics {
	if j == nil {
		return nil
	}
	return j.Logics
}

func (j *JourneyCreationRequest) GetLogicsV4() any {
	if j == nil {
		return nil
	}
	return j.LogicsV4
}

func (j *JourneyCreationRequest) GetName() string {
	if j == nil {
		return ""
	}
	return j.Name
}

func (j *JourneyCreationRequest) GetOrganizationID() string {
	if j == nil {
		return ""
	}
	return j.OrganizationID
}

func (j *JourneyCreationRequest) GetProtected() *bool {
	if j == nil {
		return nil
	}
	return j.Protected
}

func (j *JourneyCreationRequest) GetProtectedEditable() []string {
	if j == nil {
		return nil
	}
	return j.ProtectedEditable
}

func (j *JourneyCreationRequest) GetRules() []JourneyCreationRequestRules {
	if j == nil {
		return nil
	}
	return j.Rules
}

func (j *JourneyCreationRequest) GetSettings() *JourneyCreationRequestSettings {
	if j == nil {
		return nil
	}
	return j.Settings
}

func (j *JourneyCreationRequest) GetSteps() []JourneyCreationRequestSteps {
	if j == nil {
		return []JourneyCreationRequestSteps{}
	}
	return j.Steps
}

func (j *JourneyCreationRequest) GetUpdatedBy() *string {
	if j == nil {
		return nil
	}
	return j.UpdatedBy
}

func (j *JourneyCreationRequest) GetValidationRules() any {
	if j == nil {
		return nil
	}
	return j.ValidationRules
}
