// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type S3Reference struct {
	Bucket string `json:"bucket"`
	Key    string `json:"key"`
}

func (s *S3Reference) GetBucket() string {
	if s == nil {
		return ""
	}
	return s.Bucket
}

func (s *S3Reference) GetKey() string {
	if s == nil {
		return ""
	}
	return s.Key
}

// #region class-body-s3reference
// #endregion class-body-s3reference
