// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-journey/internal/sdk/internal/utils"
	"time"
)

type CreatedBy struct {
	// User ID
	ID *string `json:"id,omitempty"`
}

func (c *CreatedBy) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

// JourneyVersion - Journey Version
type JourneyVersion string

const (
	JourneyVersionFlex JourneyVersion = "Flex"
)

func (e JourneyVersion) ToPointer() *JourneyVersion {
	return &e
}
func (e *JourneyVersion) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Flex":
		*e = JourneyVersion(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JourneyVersion: %v", v)
	}
}

type Results struct {
	CreatedAt *time.Time `json:"_created_at,omitempty"`
	// Journey Entity ID
	ID *string `json:"_id,omitempty"`
	// Manifest ID used to create/update the entity
	Manifest []string `json:"_manifest,omitempty"`
	// Organization ID
	Org *string `json:"_org,omitempty"`
	// Entity Schema (journey always in this case)
	Schema *string  `json:"_schema,omitempty"`
	Tags   []string `json:"_tags,omitempty"`
	// Journey Entity Title
	Title     *string     `json:"_title,omitempty"`
	UpdatedAt *time.Time  `json:"_updated_at,omitempty"`
	CreatedBy []CreatedBy `json:"created_by,omitempty"`
	// Journey Design Name
	Design *string `json:"design,omitempty"`
	// Journey config ID
	JourneyID *string `json:"journey_id,omitempty"`
	// Journey Name
	JourneyName *string `json:"journey_name,omitempty"`
	// Journey Template
	JourneyType *string `json:"journey_type,omitempty"`
	// Journey Version
	JourneyVersion *JourneyVersion `json:"journey_version,omitempty"`
}

func (r Results) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *Results) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *Results) GetCreatedAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.CreatedAt
}

func (r *Results) GetID() *string {
	if r == nil {
		return nil
	}
	return r.ID
}

func (r *Results) GetManifest() []string {
	if r == nil {
		return nil
	}
	return r.Manifest
}

func (r *Results) GetOrg() *string {
	if r == nil {
		return nil
	}
	return r.Org
}

func (r *Results) GetSchema() *string {
	if r == nil {
		return nil
	}
	return r.Schema
}

func (r *Results) GetTags() []string {
	if r == nil {
		return nil
	}
	return r.Tags
}

func (r *Results) GetTitle() *string {
	if r == nil {
		return nil
	}
	return r.Title
}

func (r *Results) GetUpdatedAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.UpdatedAt
}

func (r *Results) GetCreatedBy() []CreatedBy {
	if r == nil {
		return nil
	}
	return r.CreatedBy
}

func (r *Results) GetDesign() *string {
	if r == nil {
		return nil
	}
	return r.Design
}

func (r *Results) GetJourneyID() *string {
	if r == nil {
		return nil
	}
	return r.JourneyID
}

func (r *Results) GetJourneyName() *string {
	if r == nil {
		return nil
	}
	return r.JourneyName
}

func (r *Results) GetJourneyType() *string {
	if r == nil {
		return nil
	}
	return r.JourneyType
}

func (r *Results) GetJourneyVersion() *JourneyVersion {
	if r == nil {
		return nil
	}
	return r.JourneyVersion
}

type SearchJourneysResponse struct {
	// The total number of hits.
	//
	Hits *float64 `json:"hits,omitempty"`
	// The results.
	//
	Results []Results `json:"results,omitempty"`
}

func (s *SearchJourneysResponse) GetHits() *float64 {
	if s == nil {
		return nil
	}
	return s.Hits
}

func (s *SearchJourneysResponse) GetResults() []Results {
	if s == nil {
		return nil
	}
	return s.Results
}
