// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// CustomMargins - Custom margins for the document
type CustomMargins struct {
	// Bottom margin in cm
	Bottom *float64 `json:"bottom,omitempty"`
	// Top margin in cm
	Top *float64 `json:"top,omitempty"`
}

func (o *CustomMargins) GetBottom() *float64 {
	if o == nil {
		return nil
	}
	return o.Bottom
}

func (o *CustomMargins) GetTop() *float64 {
	if o == nil {
		return nil
	}
	return o.Top
}

// SuggestedMargins - Suggested margins for the document
type SuggestedMargins struct {
	// Bottom margin in cm
	Bottom *float64 `json:"bottom,omitempty"`
	// Top margin in cm
	Top *float64 `json:"top,omitempty"`
}

func (o *SuggestedMargins) GetBottom() *float64 {
	if o == nil {
		return nil
	}
	return o.Bottom
}

func (o *SuggestedMargins) GetTop() *float64 {
	if o == nil {
		return nil
	}
	return o.Top
}

// TemplateSettings - Template Settings for document generation
type TemplateSettings struct {
	// Custom margins for the document
	CustomMargins *CustomMargins `json:"custom_margins,omitempty"`
	// Display margin guidelines (applicable to partial generation only)
	DisplayMarginGuidelines *bool `json:"display_margin_guidelines,omitempty"`
	// Enable data table margin autofix
	EnableDataTableMarginAutofix *bool `json:"enable_data_table_margin_autofix,omitempty"`
	// Enables the persistance of template settings
	EnabledTemplateSettingsPersistence *bool `json:"enabled_template_settings_persistence,omitempty"`
	// The file entity id, used when persisting a new template version with updated settings
	FileEntityID *string `json:"file_entity_id,omitempty"`
	// An indication that the page margins are misconfigured
	MisconfiguredMargins *bool `json:"misconfigured_margins,omitempty"`
	// Suggested margins for the document
	SuggestedMargins *SuggestedMargins `json:"suggested_margins,omitempty"`
	// A flag that indicates whether the template has 1 or more data tables in it
	TemplateWithDatatable *bool `json:"template_with_datatable,omitempty"`
}

func (o *TemplateSettings) GetCustomMargins() *CustomMargins {
	if o == nil {
		return nil
	}
	return o.CustomMargins
}

func (o *TemplateSettings) GetDisplayMarginGuidelines() *bool {
	if o == nil {
		return nil
	}
	return o.DisplayMarginGuidelines
}

func (o *TemplateSettings) GetEnableDataTableMarginAutofix() *bool {
	if o == nil {
		return nil
	}
	return o.EnableDataTableMarginAutofix
}

func (o *TemplateSettings) GetEnabledTemplateSettingsPersistence() *bool {
	if o == nil {
		return nil
	}
	return o.EnabledTemplateSettingsPersistence
}

func (o *TemplateSettings) GetFileEntityID() *string {
	if o == nil {
		return nil
	}
	return o.FileEntityID
}

func (o *TemplateSettings) GetMisconfiguredMargins() *bool {
	if o == nil {
		return nil
	}
	return o.MisconfiguredMargins
}

func (o *TemplateSettings) GetSuggestedMargins() *SuggestedMargins {
	if o == nil {
		return nil
	}
	return o.SuggestedMargins
}

func (o *TemplateSettings) GetTemplateWithDatatable() *bool {
	if o == nil {
		return nil
	}
	return o.TemplateWithDatatable
}
