// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// CustomMargins - Custom margins for the document
type CustomMargins struct {
	// Bottom margin in cm
	Bottom *float64 `json:"bottom,omitempty"`
	// Top margin in cm
	Top *float64 `json:"top,omitempty"`
}

func (c *CustomMargins) GetBottom() *float64 {
	if c == nil {
		return nil
	}
	return c.Bottom
}

func (c *CustomMargins) GetTop() *float64 {
	if c == nil {
		return nil
	}
	return c.Top
}

// SuggestedMargins - Suggested margins for the document
type SuggestedMargins struct {
	// Bottom margin in cm
	Bottom *float64 `json:"bottom,omitempty"`
	// Top margin in cm
	Top *float64 `json:"top,omitempty"`
}

func (s *SuggestedMargins) GetBottom() *float64 {
	if s == nil {
		return nil
	}
	return s.Bottom
}

func (s *SuggestedMargins) GetTop() *float64 {
	if s == nil {
		return nil
	}
	return s.Top
}

// TemplateSettings - Template Settings for document generation
type TemplateSettings struct {
	// Custom margins for the document
	CustomMargins *CustomMargins `json:"custom_margins,omitempty"`
	// Display margin guidelines (applicable to partial generation only)
	DisplayMarginGuidelines *bool `json:"display_margin_guidelines,omitempty"`
	// Enable data table margin autofix
	EnableDataTableMarginAutofix *bool `json:"enable_data_table_margin_autofix,omitempty"`
	// Enables the persistance of template settings
	EnabledTemplateSettingsPersistence *bool `json:"enabled_template_settings_persistence,omitempty"`
	// The file entity id, used when persisting a new template version with updated settings
	FileEntityID *string `json:"file_entity_id,omitempty"`
	// An indication that the page margins are misconfigured
	MisconfiguredMargins *bool `json:"misconfigured_margins,omitempty"`
	// Suggested margins for the document
	SuggestedMargins *SuggestedMargins `json:"suggested_margins,omitempty"`
	// A flag that indicates whether the template has 1 or more data tables in it
	TemplateWithDatatable *bool `json:"template_with_datatable,omitempty"`
}

func (t *TemplateSettings) GetCustomMargins() *CustomMargins {
	if t == nil {
		return nil
	}
	return t.CustomMargins
}

func (t *TemplateSettings) GetDisplayMarginGuidelines() *bool {
	if t == nil {
		return nil
	}
	return t.DisplayMarginGuidelines
}

func (t *TemplateSettings) GetEnableDataTableMarginAutofix() *bool {
	if t == nil {
		return nil
	}
	return t.EnableDataTableMarginAutofix
}

func (t *TemplateSettings) GetEnabledTemplateSettingsPersistence() *bool {
	if t == nil {
		return nil
	}
	return t.EnabledTemplateSettingsPersistence
}

func (t *TemplateSettings) GetFileEntityID() *string {
	if t == nil {
		return nil
	}
	return t.FileEntityID
}

func (t *TemplateSettings) GetMisconfiguredMargins() *bool {
	if t == nil {
		return nil
	}
	return t.MisconfiguredMargins
}

func (t *TemplateSettings) GetSuggestedMargins() *SuggestedMargins {
	if t == nil {
		return nil
	}
	return t.SuggestedMargins
}

func (t *TemplateSettings) GetTemplateWithDatatable() *bool {
	if t == nil {
		return nil
	}
	return t.TemplateWithDatatable
}
