// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type JourneyCreationRequestV2Logics struct {
	Actions         []types.String `tfsdk:"actions"`
	AutoGeneratedID types.String   `tfsdk:"auto_generated_id"`
	Conditions      []types.String `tfsdk:"conditions"`
}
