// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type JourneyCreationRequestV2EmbedOptions struct {
	Button      *JourneyCreationRequestV2Button `tfsdk:"button"`
	Lang        types.String                    `tfsdk:"lang"`
	Mode        types.String                    `tfsdk:"mode"`
	ScrollToTop types.Bool                      `tfsdk:"scroll_to_top"`
	TopBar      types.Bool                      `tfsdk:"top_bar"`
	Width       types.String                    `tfsdk:"width"`
}
