// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type JourneyCreationRequestV2ContextSchema struct {
	IsRequired types.Bool   `tfsdk:"is_required"`
	ParamKey   types.String `tfsdk:"param_key"`
	Type       types.String `tfsdk:"type"`
}
