// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type JourneyCreationRequestV2Button struct {
	Align types.String `tfsdk:"align"`
	Text  types.String `tfsdk:"text"`
}
