// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type JourneyCreationRequestV2Rules struct {
	Source     types.String `tfsdk:"source"`
	SourceType types.String `tfsdk:"source_type"`
	Target     types.String `tfsdk:"target"`
	Type       types.String `tfsdk:"type"`
}
