// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type JourneyCreationRequestV2Design struct {
	LogoURL types.String            `tfsdk:"logo_url"`
	Theme   map[string]types.String `tfsdk:"theme"`
}
