// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type JourneyCreationRequestV2Design struct {
	DesignTokens *JourneyCreationRequestV2DesignTokens `tfsdk:"design_tokens"`
	LogoURL      types.String                          `tfsdk:"logo_url"`
	Theme        map[string]jsontypes.Normalized       `tfsdk:"theme"`
}
