// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type JourneyCreationRequestV2Settings struct {
	AccessMode                types.String                          `tfsdk:"access_mode"`
	AddressSuggestionsFileID  types.String                          `tfsdk:"address_suggestions_file_id"`
	AddressSuggestionsFileURL types.String                          `tfsdk:"address_suggestions_file_url"`
	Description               types.String                          `tfsdk:"description"`
	DesignID                  types.String                          `tfsdk:"design_id"`
	EmbedOptions              *JourneyCreationRequestV2EmbedOptions `tfsdk:"embed_options"`
	EntityID                  types.String                          `tfsdk:"entity_id"`
	EntityTags                []types.String                        `tfsdk:"entity_tags"`
	FilePurposes              []types.String                        `tfsdk:"file_purposes"`
	MappingsAutomationID      types.String                          `tfsdk:"mappings_automation_id"`
	RuntimeEntities           []types.String                        `tfsdk:"runtime_entities"`
	SafeModeAutomation        types.Bool                            `tfsdk:"safe_mode_automation"`
	TargetedCustomer          types.String                          `tfsdk:"targeted_customer"`
	TemplateID                types.String                          `tfsdk:"template_id"`
}
