// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-journey/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetJourneyRequest struct {
	// Journey ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Organization ID
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (o *GetJourneyRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetJourneyRequest) GetOrgID() *string {
	if o == nil {
		return nil
	}
	return o.OrgID
}

type GetJourneyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	JourneyResponse *shared.JourneyResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetJourneyResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetJourneyResponse) GetJourneyResponse() *shared.JourneyResponse {
	if o == nil {
		return nil
	}
	return o.JourneyResponse
}

func (o *GetJourneyResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetJourneyResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
